sdrgui/gui/valuedial.cpp, sdrgui/gui/valuedialz.cpp
Adds termination to QWheelEvent so it wont sent to parent Window.
as described here:
http://www.setnode.com/blog/mouse-wheel-events-event-filters-and-qscrollarea/
I confirm this fixes Issue #132 for me.
=> fix QtWheelEvent propagation in valuedial and valuedialz

cmake/Modules/FindLibHACKRF.cmake
I was wondering why the CMake configuration step did not find `libhackrf` although it was installed correctly and worked with other application:
```
-- libhackrf not found.
```
After fixing the obviously wrong library name for the CMake find module (probably caused by copy & paste error) the detection of `libhackrf` now worked correctly as seen below:
```
-- Checking for module 'libhackrf'
--   Found libhackrf, version 0.5
-- Found libhackrf: /usr/local/include, /usr/local/lib/libhackrf.dylib
```
Note: I've currently only tested this on macOS - but other systems are affected as well.
=> Fix wrong library name in CMake module for hackrf

plugins/samplesource/airspy/airspyinput.cpp, plugins/samplesource/airspyhf/airspyhfinput.cpp, plugins/samplesource/bladerfinput/bladerfinput.cpp, plugins/samplesource/fcdpro/fcdproinput.cpp, plugins/samplesource/fcdproplus/fcdproplusinput.cpp, plugins/samplesource/hackrfinput/hackrfinput.cpp, plugins/samplesource/limesdrinput/limesdrinput.cpp, plugins/samplesource/perseus/perseusinput.cpp, plugins/samplesource/plutosdrinput/plutosdrinput.cpp, plugins/samplesource/rtlsdr/rtlsdrinput.cpp, plugins/samplesource/sdrdaemonsource/sdrdaemonsourceinput.cpp, plugins/samplesource/sdrplay/sdrplayinput.cpp, plugins/samplesource/testsource/testsourceinput.cpp, sdrbase/dsp/filerecord.cpp, sdrbase/dsp/filerecord.h
i changed the file name to be compatible to Microsoft Windows file systems.
i also moved the generation of those file names to a method `genUniqueFileName` in `FileRecord`, then it is easier to maintain FileName generation.
BTW: on other places, i saw, that there is often "**hh**:mm:ss" used to format QTime/QDateTime to a QString.
maybe it is better to use "**HH**:mm:ss" to force **24**h format instead of only **12**h format in some cases.
[Format QTime to QString](http://doc.qt.io/qt-5/qtime.html#toString-2)
=> modified unique file name

logging/filelogger.cpp, logging/filelogger.h, logging/fileloggersettings.h, logging/logger.cpp, logging/logger.h, logging/logmessage.h, plugins/channelrx/demodbfm/bfmdemodgui.cpp, plugins/channelrx/demoddsd/dsdstatustextdialog.cpp, plugins/channeltx/modam/ammodgui.cpp, plugins/channeltx/modatv/atvmodgui.cpp, plugins/channeltx/modnfm/nfmmodgui.cpp, plugins/channeltx/modssb/ssbmodgui.cpp, plugins/channeltx/modwfm/wfmmodgui.cpp, plugins/samplesink/filesink/filesinkgui.cpp, plugins/samplesink/sdrdaemonsink/readme.md, plugins/samplesink/sdrdaemonsink/sdrdaemonsinkgui.cpp, plugins/samplesource/filesource/filesourcegui.cpp, plugins/samplesource/sdrdaemonsource/readme.md, plugins/samplesource/sdrdaemonsource/sdrdaemonsourcegui.cpp, sdrgui/gui/commandoutputdialog.cpp, sdrgui/mainwindow.cpp, sdrgui/readme.md
changed **hh**:mm to **HH**:mm
changed **dd.MM.yyyy** to **yyyy-MM-dd** to uniform date format
maybe the changed date format will break some logging processing of the **sdrangel.log** file, when it is processed with scripts that are expecting the **dd.MM.yyyy** format.
=> force 24h time format and uniform date format

sdrgui/gui/glspectrum.cpp, sdrgui/gui/glspectrum.h, sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/glspectrumgui.h, sdrgui/gui/glspectrumgui.ui
hello,
after i was reading your posts again, i realized you gave me the hint, that the red Hold line is made in the glspectrum.
i added an option "Test Hold", where you can toggle the Hold to infinite...
like i tried to archive in issue https://github.com/f4exb/sdrangel/issues/207
it is maybe not the best implementation and naming...
but maybe you find it useful.
=> added option for test Hold

devices/plutosdr/deviceplutosdrbox.cpp, devices/plutosdr/deviceplutosdrbox.h, plugins/samplesource/plutosdrinput/plutosdrinput.cpp, plugins/samplesource/plutosdrinput/plutosdrinput.h, plugins/samplesource/plutosdrinput/plutosdrinputgui.cpp
When updating firmware, the devices which have AD9364s on them, get
reset to the default of a AD9363 (tuning range of 325 to 3800 MHz).
SDRAngel assumes a AD9364, and the GUI allows you to set LO settings
that the firmware doesn't support.
This ensures that does not happen, by going out to the hardware, and
querying the device to set the min/max limits on LO.
Signed-off-by: Robin Getz <robin.getz@analog.com>
=> pluto: Get LO range from device

devices/plutosdr/deviceplutosdrbox.cpp, devices/plutosdr/deviceplutosdrbox.h, plugins/samplesink/plutosdroutput/plutosdroutput.cpp, plugins/samplesink/plutosdroutput/plutosdroutput.h, plugins/samplesink/plutosdroutput/plutosdroutputgui.cpp, plugins/samplesource/plutosdrinput/plutosdrinput.cpp, plugins/samplesource/plutosdrinput/plutosdrinput.h, plugins/samplesource/plutosdrinput/plutosdrinputgui.cpp
This will use the RF bandwidth from the device, which is different
between AD9363 and AD9364.
Things are now managed like the device likes - analog low pass bandwidth
is RF (complex) bandwidth, not baseband single I or Q bandwidth.
Signed-off-by: Robin Getz <robin.getz@analog.com>
=> plutosdr: grab the RF bandwidth range from the device

plugins/channeltx/modssb/ssbmod.cpp
This patch fixes #294. Seems to have been a copy&paste-issue.
=> fix SSB modulator configuration API query

plugins/channeltx/modssb/ssbmod.cpp, plugins/channeltx/modssb/ssbmodgui.cpp
This commit fixes #296. The API now expects positive values for bandwidth and cutoff and respects the setting of the USB flag in the query. This makes the expected parameters consistent with the ones provided.
=> respect USB flag for SSBMod REST API calls

sdrgui/mainwindow.cpp, sdrgui/mainwindow.h, sdrgui/readme.md
This fixes #297. Keyboard commands stay enabled until explicitly disabled or program closed.
=> Don't intentionally disable keyboard commands on application focus change

CMakeLists.txt, devices/perseus/deviceperseusscan.cpp, plugins/samplesource/CMakeLists.txt, plugins/samplesource/fcdpro/CMakeLists.txt, plugins/samplesource/fcdproplus/CMakeLists.txt
I checked and now seems to works and no more error from alsa. Probably the error was library_include dependant.
=> re-enable fcdpro/fcdproplus on macOS and perseus fix

CMakeLists.txt, fcdhid/CMakeLists.txt, fcdhid/hid-libusb.c
* udev fixes 07c1413c
* usb fixes 760e4859
tested on Ubuntu 18.04 and macOS
=> udev on Linux and libusb fix

CMakeLists.txt
I don't understand why it is fixed and here
=> remove Qt framework forcing on CMAKE_PREFIX_PATH

plugins/samplesource/filesource/filesourceinput.cpp
Opening of file named `Ы.sdriq` with FileSource plugin on Windows platform results in error.
To fix this either `std::wstring` should be used in `m_ifstream.open()` call or code should be rewritten to use `QFile` instead of `std::ifstream`.
This PR implements `wstring` solution. Hope it will not break other platforms' build.
Fixes #205.
=> Use correct encoding for file names in FileSource plugin

sdrgui/mainwindow.cpp
Changing of master timer type to `Qt::PreciseTimer` makes spectrum animation more smooth on Windows platform.
Here is the video with the same record being played.
On the left is original 4.8.2 version, on the right - with this patch applied.
[sdrangel_master_timer_precision.zip](https://github.com/f4exb/sdrangel/files/3244447/sdrangel_master_timer_precision.zip)
=> Improve precision of master timer

.gitignore, flatpak/org.sdrangel.SDRangel.json, flatpak/sdrangel.desktop
@f4exb FYI: The commit hashes are taken from the Docker build with one exception. I had to update XTRX commit to `9586a6e`. Background: Flatpak (as of version 1.4.1) cannot resolve configured Git submodules where only the `gitlink` was removed, but not the corresponding configuration entry.
Known Build Issues:
TODO:
=> WIP: Flatpak packaging

flatpak/org.sdrangel.SDRangel.appdata.xml, flatpak/org.sdrangel.SDRangel.json, flatpak/sdrangel-fix-icon-file.patch, flatpak/sdrangel-set-serialdv-path.patch, flatpak/uhd-disable-ascii-art-dft.patch, flatpak/uhd-disable-latency-utils.patch
It took me some time, but I finally managed to make the SDRangel Flatpak working! I have also fixed the AppData file to make it pass the validation (feel free to edit the metadata license to the one you want, I have chosen the _CC0-1.0_ one because it is the mostly used metadata license).
SDRangel now builds and runs fine, there is, however, an issue that I was not able to fix:
- Some (optional) dependencies were not found although they are built and properly installed:
```
-- Checking for module 'libbladerf>=2.0'
--   Package 'libbladerf', required by 'virtual:world', not found
-- Checking for module 'libperseus'
--   Package 'libperseus', required by 'virtual:world', not found
-- Found libperseus: /app/include, /app/lib/libperseus-sdr.so
-- Checking for module 'soapysdr>=0.4.0'
-- …
```
=> Fix the Flatpak

plugins/channelrx/demoddatv/leansdr/dvbs2.h
- plscodes.LENGTH
llvm < 3.9.0 doesn't support "Variable length array" and therefore
can't be used (it is not part of c++11 standard). see commit
https://github.com/llvm/llvm-project/commit/e7545b33ff79c55d08d78a35b052e494ea49a0bc
- float casting is needed to avoid confusione between double and float
- F_SETPIPE_SZ is not supported on macOS
=> leansdr: fixes for macos

cmake/Modules/FindSoapySDR.cmake
This Pull Request adds a case-sensitive alternative to the CMake's `pkg_check_modules` function (`SoapySDR` and `soapysdr`). The current code couldn't find the current version of SoapySDR automatically.
=> Fixing CMake PkgConfig for the SoapySDR Module 

plugins/channelrx/CMakeLists.txt
DATV will be excluded when the ffmpeg binary is not installed,
although the actual dependencies are fulfilled.
=> Use CMake varialbles instead of depending on FFmpeg binary

plugins/channelrx/demodatv/atvdemod.h, plugins/channelrx/demodatv/atvdemodbaseband.h, plugins/channelrx/demodatv/atvdemodgui.cpp, plugins/channelrx/demodatv/atvdemodgui.ui, plugins/channelrx/demodatv/atvdemodsink.cpp, plugins/channelrx/demodatv/atvdemodsink.h, sdrgui/CMakeLists.txt, sdrgui/gui/glshadertvarray.cpp, sdrgui/gui/glshadertvarray.h, sdrgui/gui/tvscreen.cpp, sdrgui/gui/tvscreenanalog.cpp, sdrgui/gui/tvscreenanalog.h
Here is my vision of how analog TV samples should be converted to digital pixels.
These commits introduce new class: `TVScreenAnalog`.
Which is capable of shifting each individual line with subsample precision.
With it comes `TVScreenAnalogData`, which contains image and line shifts data.
Since new screen now allows independent shifts, HSync algorithm is reworked.
New TV screen uses shaders to accomplish its tasks.
Because of this, it should be tested on various hardware.
As GPU drivers can contain bugs and execute shaders command wrong.
With separate test program > 1000 FPS was obtained with this shader.
Main time consumer in render function is texture copy command.
So shader is not needed to be optimized further right now.
CPU consumption should stay approximately at the same level.
Or …
=> ATV Demod: introducing of new analog TV shader

plugins/channelrx/demodatv/atvdemodsink.cpp, plugins/channelrx/demodatv/atvdemodsink.h, sdrgui/gui/tvscreenanalog.cpp, sdrgui/gui/tvscreenanalog.h
This change is made to combat [screen tearing](https://en.wikipedia.org/wiki/Screen_tearing) problem. Like this:
This change is simple.
Hope that I did not break something.
=> ATV Demodulator: implement double buffering

plugins/channeltx/modatv/atvmodsource.cpp
=> ATV Modulator: fix crash when m_pointsPerHBar = 0

devices/plutosdr/deviceplutosdrbox.cpp, devices/plutosdr/deviceplutosdrbox.h, plugins/samplesource/plutosdrinput/plutosdrinputthread.cpp
Correctly open I and Q channels for RX sampling.
See: https://github.com/f4exb/sdrangel/issues/604
=> Fix libiio channel handling for IQ sampling with plutosdr

sdrbase/dsp/filerecord.cpp
I noticed that .sdriq files contain two headers. One is written in FileRecord::startRecording() when the file is opened and the next one in FileRecord::feed when the first samples are written.
From the documentation of the plugin, I assume that there should be only one header.
=> Only write .sqriq header once when the first samples are written

plugins/samplesink/fileoutput/fileoutputgui.cpp, plugins/samplesink/testsink/testsinkgui.cpp
This PR increases the supported sample rates in the file output and test sink plugins by 10x from 9MSa/s to 90MSa/s. This is needed because I'm testing a modulator plugin that requires a sample rate greater than 9MSa/s.
=> Increase supported sample rate in fileoutput and testsink by 10x

plugins/samplesource/fcdproplus/fcdproplusplugin.cpp
Although the plugin is loaded and the device attached, fcdpro+ is not shown up in the list of available samplin devices.
This patch makes the fcdpro+ device visible.
=> FCDPro+ not visible

sdrsrv/feature/featureset.h
The current head fails to link on Windows for me, with:
webapiadaptersrv.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: int __cdecl FeatureSet:
:getNumberOfFeatures(void)const " (__imp_?getNumberOfFeatures@FeatureSet@@QEBAHXZ) 
Removing SDRGUI_API from the class declaration fixes it.
(I'm not sure why your automated Windows build doesn't have the same problem too?)
=> Remove SDRGUI_API to allow linking on Windows

plugins/feature/rigctlserver/rigctlserverworker.cpp
This adds the `cmath` include to rigctlserverworker.cpp so the `std::abs()` on double overload is defined. Otherwise I get
```
plugins/feature/rigctlserver/rigctlserverworker.cpp:361:27: error: call to 'abs' is ambiguous
bool outOfRange = std::abs(freq - targetFrequency) > m_settings.m_maxFrequencyOffset;
^~~~~~~~
/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) ;
^
```
=> Fix missing cmath include

plugins/channelrx/demodadsb/adsbdemoddisplaydialog.cpp, plugins/channelrx/demodadsb/adsbdemoddisplaydialog.h, plugins/channelrx/demodadsb/adsbdemoddisplaydialog.ui, plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodadsb/adsbdemodgui.h, plugins/channelrx/demodadsb/adsbdemodgui.ui, plugins/channelrx/demodadsb/adsbdemodsettings.cpp, plugins/channelrx/demodadsb/adsbdemodsettings.h, plugins/channelrx/demodadsb/adsbdemodsink.cpp, plugins/channelrx/demodadsb/map/map.qml, plugins/channelrx/demodadsb/osndb.h, plugins/channelrx/demodadsb/ourairportsdb.h, plugins/channelrx/demodadsb/readme.md
Hi Edouard,
This PR incudes some changes based on your feedback of the previous release, and also some additional bug fixes and improvements:
Add decode of Mode-A transponder (Squawk) code
Add decoding of surface position messages (so you can see aircraft position at airports)
Add Az/El and distance to airport information box
Require double click to set ATC frequency.
Allow airport to be set as target, by double clicking Az/El in airport info box.
Confirm redownload of files if less than 100 days old.
Add option to automatically resize columns after an aircraft is added to the table.
Check latitude and local CPR decode is in valid range (to prevent aircraft from jumping around the map).
Reduce interpolator taps to enable it to run in real-time. Should significantly improve packet error …
=> ADS-B improvements

sdrbase/pipes/elementpipesgc.h, sdrbase/pipes/elementpipesregistrations.h
Hi,
It seems the pipe garbage collection can crash after a feature has been removed. As a example (on Windows at least)
- Run SDRangel and create VOR SC channel demod and VOR localiser
- Run them for a bit
- Delete the demod 
- Delete the localiser
After a few seconds, SDRangel will crash. (I actually noticed the problem when trying to change the ADSBDemod and GS232 Controller to use the pipes).
A possible fix to elementpipesgc.h is to check that the consumer exists before sending the message.
While debugging, I also noticed a compiler warning of the use of an uninitialized variable in elementpipesregistrations.h - while the m_typeCount variable isn't being used. So the change there is just a guess at what you might have been trying to do, but I'm not certain, so you probably need to take …
=> Fix crash in pipe garbage collection

plugins/feature/startracker/CMakeLists.txt, plugins/feature/startracker/startracker.qrc, plugins/feature/startracker/startracker1420mhz.qrc, plugins/feature/startracker/startracker150mhz.qrc, plugins/feature/startracker/startracker408mhz.qrc, plugins/feature/startracker/startrackergui.cpp
As per the mailing list, Star Tracker was failing to compile on PI4. This appears to be due to gcc using an insane amount of memory when compiling the resource files. So I've split them in to several resource files. I don't have a PI to test, but uses ~75% less RAM on x64.
=> Star tracker separate resources

plugins/samplesource/fileinput/fileinput.cpp, plugins/samplesource/fileinput/fileinput.h, plugins/samplesource/fileinput/fileinputgui.cpp, plugins/samplesource/fileinput/fileinputgui.h, plugins/samplesource/fileinput/fileinputsettings.cpp
This patch:
- Allows the filename for the file input source to be restored from settings
- Allows the filename to be set via the API
For testing, I quite often replay data from files, so saves a bit of time having the last file automatically opened. There was already an entry in the settings structure, but wasn't being used.
=> File Input source filename settings

plugins/channelrx/chanalyzer/chanalyzer.cpp, plugins/channelrx/chanalyzer/chanalyzergui.cpp, plugins/channelrx/chanalyzer/chanalyzergui.h, plugins/channelrx/chanalyzer/chanalyzergui.ui, plugins/channelrx/chanalyzer/chanalyzersettings.cpp, plugins/channelrx/chanalyzer/chanalyzersettings.h, plugins/channelrx/chanalyzer/chanalyzersink.cpp, plugins/channelrx/chanalyzer/chanalyzersink.h, plugins/channelrx/chanalyzer/chanalyzerwebapiadapter.cpp, sdrbase/CMakeLists.txt, sdrbase/dsp/costasloop.cpp, sdrbase/dsp/costasloop.h, sdrbase/resources/webapi/doc/html2/index.html, sdrbase/resources/webapi/doc/swagger/include/ChannelAnalyzer.yaml, swagger/sdrangel/api/swagger/include/ChannelAnalyzer.yaml, swagger/sdrangel/code/html2/index.html, swagger/sdrangel/code/qt5/client/SWGChannelAnalyzerSettings.cpp, swagger/sdrangel/code/qt5/client/SWGChannelAnalyzerSettings.h
This patch:
- Adds a Costas loop PLL to the channel analyzer
- Adds loop bandwidth and other PLL controls to Channel Analyzer GUI.
- Fixes bug where PLL lock frequency is incorrectly scaled by the decimation factor.
Costas loop should somewhat combine existing PLL and FLL functionality, providing both frequency and phase lock. Seems to provide a more stable lock too in the brief testing I've done.  
Happy to change the way the GUI hides the extra widgets when PLL is disabled, if you don't like it, but I thought that would keep the GUI a bit simpler in most use cases where the PLL isn't being used.
=> Add Costas loop PLL to channel analyzer

plugins/feature/satellitetracker/satellitetrackerworker.cpp, plugins/samplesource/fileinput/fileinput.cpp, sdrbase/dsp/filerecord.cpp
When opening a sdriq file created by the file sink, that had been started by the satellite tracker, SDRangel was crashing. The CRC was valid, but the samplerate in the file was 0.
The crash was due to a divide by 0 - and the first commit now checks for that.
I think the reason that the samplerate in the sdriq file was written as zero, is probably due to a race condition, whereby feed() is being called around the same time as handleMessage() which sets the sample rate.
To help, I've added a lock of the mutex in handleMessage and also add a 1 second delay after the preset is loaded before the file sinks start recording. I don't think that's perfect, but it's a bit better.
=> sdriq sample rate can be zero

plugins/samplesource/hackrfinput/hackrfinput.cpp, plugins/samplesource/hackrfinput/hackrfinputgui.cpp, plugins/samplesource/hackrfinput/hackrfinputgui.h, plugins/samplesource/hackrfinput/hackrfinputgui.ui, plugins/samplesource/hackrfinput/hackrfinputsettings.cpp, plugins/samplesource/hackrfinput/hackrfinputsettings.h, plugins/samplesource/hackrfinput/readme.md
libhackrf automatically sets bandpass filter every time the sample rate is set. This was causing a settings mismatch between gui and hardware. I made a change to force the current gui setting as hardware setting when sample rate is set.
It would probably be better if libhackrf would optionally apply auto setting and report bandwidth set. However, as far as I can tell it just forces it with no ability to report. It also seems like this change to SDRangel would get approved faster than a change to libhackrf.
I also implemented a button to enable auto bandpass filter selection. This matches the setting that libhackrf was applying.
=> hackrfinput - Add auto bandpass filter selection

plugins/samplesource/hackrfinput/hackrfinput.cpp, plugins/samplesource/hackrfinput/hackrfinput.h
LO ppm now adjusts the primary clock in the hackrf one instead of offsetting the freq in software. The offset adjusts all clocks except the CPU which currently uses it's own crystal.
There is room for improvement but I tried to keep it simple and keep the user interface the same for now.
=> hackrfinput - Change LO ppm to adjust the hardware clocks.

plugins/channeltx/moddatv/datvmodgui.ui, plugins/channeltx/moddatv/datvmodsource.cpp
=> Avoid divide by 0 if symbol rate is 0.

plugins/channelrx/demoddab/dabdemodsink.cpp
=> Use UTF-8 rather than latin encoding for program names. 

plugins/channelrx/demoddab/dabdemod.h, plugins/channelrx/demoddab/dabdemodgui.cpp, plugins/channelrx/demoddab/dabdemodsink.cpp, plugins/channelrx/demoddab/dabdemodsink.h
This no longer writes MOT files to disk. There was problem with this when the broadcast filename contained a sub-directory. 
Note, this requires latest version of DAB lib on: https://github.com/srcejon/dab-cmdline.git
This may fix the last issue reported on #853 (at least it does for the .sdriq file provided).
=> Use latest DAB lib API.

plugins/channelrx/demodais/aisdemod.cpp, sdrbase/util/ais.cpp
=> Stop UDP forwarded AIS packets containing null byte from being truncated

plugins/channelrx/filesink/filesinkgui.cpp, plugins/channelrx/filesink/filesinksink.cpp, plugins/channelrx/filesink/filesinksink.h, plugins/channelrx/filesink/readme.md, plugins/samplesource/fileinput/fileinput.cpp, plugins/samplesource/fileinput/fileinputgui.cpp, plugins/samplesource/fileinput/readme.md, sdrbase/CMakeLists.txt, sdrbase/dsp/filerecord.cpp, sdrbase/dsp/filerecord.h, sdrbase/dsp/filerecordinterface.cpp, sdrbase/dsp/filerecordinterface.h, sdrbase/dsp/sigmffilerecord.h, sdrbase/dsp/wavfilerecord.cpp, sdrbase/dsp/wavfilerecord.h
This PR adds signed 16-bit PCM  .wav file support to the File Input and File Sink plugins.
I find this useful, as it's easier to use these files with other tools for analysis and editing.
While .wav can support 32-bit, I made this 16-bit as an option to have a reduced file size. Capturing data at several MSa/s results in very large files and at these sort of rates I don't think the extra bits are really useful. (In the future, could add an option to select 8/16/32-bit capture for either file type, but that needs a little more work).
This supports the .wav auxi header used by some other signal processing s/w to save centre frequency and start time, so functionality shouldn't be reduced in comparison to .sdriq. It can also work this info out from the filename used by a couple of other SDR …
=> Add .wav file support for File Input and File Sink

devices/plutosdr/deviceplutosdrscan.cpp, devices/plutosdr/deviceplutosdrscan.h
Fixes #681.
Relying on memory allocated by `std::vector` via direct pointers is dangerous, as vectors may move buffers during resize. This fix puts the `DeviceScan` allocation into a `str::shared_ptr`, which 1) allocates the memory on heap and 2) keeps track of the memory through reference counting. Thus it is safe to store the `shared_ptr` across different vectors/maps.
=> Use shared_ptr to keep track of DeviceScan across multiple collections

plugins/channelrx/demodadsb/adsbdemod.cpp
Fixes #915.
As described in the issue, during deconstruction of [`ADSBDemod`](https://github.com/f4exb/sdrangel/blob/3e9b4a4dee67dd37a9bcdd90c00c5141550c189d/plugins/channelrx/demodadsb/adsbdemod.cpp#L81) a segmentation fault might occur, if `DSPDeviceSourceEngine` calls [`sink->stop()`](https://github.com/f4exb/sdrangel/blob/3e9b4a4dee67dd37a9bcdd90c00c5141550c189d/sdrbase/dsp/dspdevicesourceengine.cpp#L596) _after_ `m_worker` was deleted.
This PR fixes the issue by deleting `m_worker` only after [`m_deviceAPI->removeChannelSink(this)`](https://github.com/f4exb/sdrangel/blob/3e9b4a4dee67dd37a9bcdd90c00c5141550c189d/plugins/channelrx/demodadsb/adsbdemod.cpp#L90) is called. This call would otherwise invoke `sink->stop()` with a broken `m_worker` somewhere down the line.
=> Delete ADSBDemod::m_worker after removing sink from DSP

sdrgui/mainwindow.cpp
This patch saves and restores the main window position and size between invocations of SDRangel. Fixes #89
=> Save and restore main window position and size

plugins/feature/satellitetracker/readme.md, sdrbase/webapi/webapirequestmapper.cpp, sdrbase/webapi/webapiutils.cpp
Add SatelliteTracker to webapirequestmapper to partially fix #948
This allows basic settings to be set, i.e. target satellite, but it seems there's a null pointer exception when trying to set "satellites" which uses a string array.
=> Add SatelliteTracker to webapirequestmapper to partially fix #948

plugins/feature/satellitetracker/satellitetracker.cpp, plugins/feature/satellitetracker/satellitetracker.h, plugins/feature/satellitetracker/satellitetrackergui.cpp, plugins/feature/satellitetracker/satellitetrackerworker.cpp, plugins/feature/satellitetracker/satellitetrackerworker.h
Hopefully fix #893.
Ensure LOS is signalled even if new AOS is calculated 1second before LOS.
Redirect calls to get the time via a functions in SatelliteTracker, so it can easily be adjusted for testing.
Delete some obsolete code.
=> Satellite Tracker: Fix for #893

plugins/channelrx/demodpager/pagerdemodcharsetdialog.cpp, plugins/channelrx/demodpager/pagerdemodcharsetdialog.ui, plugins/channelrx/demodpager/pagerdemodsettings.cpp, plugins/channelrx/demodpager/pagerdemodsettings.h, plugins/channelrx/demodpager/pagerdemodsink.cpp
Use reverse option, instead of right-to-left, as Hebrew appears to be transmitted last first. 
As discussed in comments on PR #960
=> Pager: Add extra Hebrew characters. 

plugins/channeltx/moddatv/datvmod.cpp, plugins/channeltx/moddatv/datvmod.h, plugins/channeltx/moddatv/datvmodbaseband.cpp, plugins/channeltx/moddatv/datvmodgui.cpp, plugins/channeltx/moddatv/datvmodgui.ui, plugins/channeltx/moddatv/datvmodreport.cpp, plugins/channeltx/moddatv/datvmodreport.h, plugins/channeltx/moddatv/datvmodsettings.h, plugins/channeltx/moddatv/datvmodsource.cpp, plugins/channeltx/moddatv/datvmodsource.h
Add a display of UDP receive buffer utilization to the DATV Modulator.
This only currently works on Windows, as the linux ioctl(s, SIOCINQ, &count); only seems to return size of first datagram, not all datagrams. So on Linux the GUI elements are currently hidden.
Should hopefully help with diagnosing issues such as #972 
Also increased buffer size to 5M
=> DATV Mod: Add UDP buffer utilization in GUI on Windows

plugins/samplesink/fileoutput/fileoutput.cpp, plugins/samplesink/fileoutput/fileoutput.h, plugins/samplesource/fileinput/fileinputgui.cpp, rescuesdriq/readme.md, rescuesdriq/rescuesdriq.go, sdrbase/dsp/filerecord.cpp
As mentioned in #980 here's my take on increasing timestamp resolution in file-headers.
While going through the references I found some golang code for converting old sdriq files to the newer format. I tried changing that as well, but I'm not too familiar with go, so please someone vet my code.
=> Higher resolution timestamp in sdriq format

.gitignore, rescuesdriq/go.mod, rescuesdriq/go.sum, rescuesdriq/readme.md, rescuesdriq/rescuesdriq.go
Enable `rescuesdriq` tool to adapt pre-v6.16.2 records to the new header format (turning seconds into milliseconds). By default, timestamps read from input files will be assumed to be in seconds and subsequently converted to milliseconds. The command-line option `-msec` disables this behavior and assumes the timestamp to already be in the desired format.
Some minimal go-project files were provided to allow easy building. Additional documentation can be found in the `/rescuesdriq/readme.md`.
=> Support pre- and post-v6.16.2 file formats in rescuesdriq

rescuesdriq/rescuesdriq.go
Fixes two major and one minor bug in rescuesdriq.
Closes #986.
=> Random bytes appended to rescuesdriq output and wrong timestamp

plugins/channelrx/demoddatv/datvdemodgui.ui
Set minimum size constraint on videoTab not just tabWidget so that window isn't too small. Let me know if it fixes the probem - it seems to for me.
(This assumes the other earlier PR is applied).
=> Set DATV GUI to be minimum sized rather than expanding. 

plugins/samplesource/remoteinput/readme.md, plugins/samplesource/remoteinput/remoteinputgui.ui, plugins/samplesource/remoteinput/remoteinputsettings.cpp
Set default value of API port to 8091, as used elsewhere in SDRangel.
Fix spelling mistakes in readme.
Update tooltip to clarify data address is for reception.
=> RemoteInput 

plugins/samplesource/rtlsdr/rtlsdrgui.cpp
Currently the biasT setting in the GUI isn't being restored to what is saved in the preset. This should fix that.
=> RTLSDR: Restore biasT widget state in displaySettings

plugins/samplesource/remoteinput/remoteinputgui.cpp, plugins/samplesource/remoteinput/remoteinputgui.h
So Set button is highlighted if focus is changed with mouse or tab as per #1031.
=> #1031 - RemoteInput GUI - Use editingFinished signal rather than returnPressed

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodvor/vordemodgui.cpp, plugins/feature/map/mapbeacondialog.cpp, plugins/feature/vorlocalizer/vorlocalizergui.cpp, sdrgui/gui/httpdownloadmanagergui.cpp
As if the user closes the window before the download is complete, a crash can occur.
=> Don't use WA_DeleteOnClose for download progress dialogs

plugins/feature/afc/afc.cpp, plugins/feature/afc/afcworker.cpp, plugins/feature/aprs/aprs.cpp, plugins/feature/aprs/aprsworker.cpp, plugins/feature/aprs/aprsworker.h, plugins/feature/demodanalyzer/demodanalyzer.cpp, plugins/feature/gs232controller/gs232controller.cpp, plugins/feature/gs232controller/gs232controllerworker.cpp, plugins/feature/pertester/pertester.cpp, plugins/feature/pertester/pertesterworker.cpp, plugins/feature/pertester/pertesterworker.h, plugins/feature/rigctlserver/rigctlserver.cpp, plugins/feature/rigctlserver/rigctlserverworker.h, plugins/feature/satellitetracker/satellitetracker.cpp, plugins/feature/satellitetracker/satellitetrackerworker.cpp, plugins/feature/satellitetracker/satellitetrackerworker.h, plugins/feature/simpleptt/simpleptt.cpp, plugins/feature/simpleptt/simplepttworker.cpp, plugins/feature/startracker/startracker.cpp, plugins/feature/startracker/startrackerworker.cpp, plugins/feature/startracker/startrackerworker.h, plugins/feature/vorlocalizer/vorlocalizer.cpp, plugins/feature/vorlocalizer/vorlocalizerworker.cpp, plugins/feature/vorlocalizer/vorlocalizerworker.h
I noticed a small bug in the first Feature that has been cut and paste to all of the others. A thread is created for the worker, but moveToThread was never called, so the worker remains on the main thread.
Aside from calling moveToThread, a few other changes needed to be made for QTimers and sockets in the workers, so they are on the correct thread:
- For those timers/sockets that are members of the worker, they needed to have their parent object set, so that they are moved to the correct thread when moveToThread is called.
- Starting of timers/opening sockets needs to occur on the worker thread rather than the main thread. So this code has been moved from startWork() / stopWork() in to the QThread::started() and QThread::finished slots.
I don't use the AFC / PTT features, so it would be …
=> Move Feature workers to thread

plugins/channelrx/demodadsb/ourairportsdb.h, plugins/channelrx/demodvor/navaid.h, plugins/channelrx/demodvor/vordemodgui.ui, plugins/feature/vorlocalizer/navaid.h
Fixes #1062 and #732
Airport locations in ADS-B plugin were at wrong locations for users with locales where decimal point is , rather than . This should fix that, by using C locale when parsing the .csv files.
Also, updates VOR demod GUI so more than one row is visible.
=> Fix #1062 - Use C locale when parsing airport/navaid files

plugins/feature/gs232controller/gs232controllergui.cpp
Don't round az/el received from Sat Tracker we now support higher precision rotators.
Fixes issue reported on mailing list.
=> Rotator controller - Don't round az/el received from Sat Tracker

plugins/channelrx/demodadsb/adsbdemod.cpp, plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodadsb/adsbdemodgui.ui, plugins/channelrx/demoddab/dabdemodgui.cpp, plugins/channelrx/demoddab/dabdemodgui.ui
As we've had several bug reports about them not working.
=> Display warnings in ADS-B and DAB if sample rate is too low

app/main.cpp, sdrgui/mainwindow.cpp, sdrgui/mainwindow.h
This patch displays the OpenGL version in the status bar, alongside the other version information. I've added this as we've had a couple of bug reports where this information seems relevant.
It is displayed in red if less than version 3, as the waterfall is unlikely to work.
=> Display OpenGL version in status bar. 

plugins/channelrx/noisefigure/noisefigure.cpp, plugins/channelrx/noisefigure/noisefigureenrdialog.cpp
Fix for #1087. Support compilation with Boost >= 1.77 while maintaining compatibility with 1.70.
=> Fix for #1087. Support compilation with Boost >= 1.77

plugins/samplesource/fileinput/fileinput.cpp
Following PR #981 for issue #980, it seems dates and times in File Input device are wrong for .wavs and the API report for absolute time for .sdriqs is wrong. This patch hopefully fixes them, by using msec instead of sec.
=> Fix File Input date time.

plugins/channelrx/demoddatv/datvideorender.cpp
As a guess at fixing the compilation issue reported on the mailing list, make AVCodecs const. Looks like the FFMpeg API has been updated.
=> DATV Demod - Make AVCodecs const

sdrgui/gui/glspectrumgui.ui, sdrgui/gui/spectrummarkersdialog.cpp, sdrgui/gui/spectrummarkersdialog.ui
Here are a few small changes to the Spectrum Marker GUI.
I've removed the checkable flag from the Open Spectrum Markers Dialog button.
I've added some additional tooltips to the Spectrum Markers Dialog, to explain some of the abbreviations.
I've hidden the fixed power level widget when the combo box is set to Cur or Max, as this setting isn't relevant for those options. I don't know if you prefer setting controls as disabled rather than hiding them, but some widgets do not appear different visually when disabled, so I thought I'd hide it instead.
=> Spectrum Marker GUI small tweaks

plugins/channelrx/demoddatv/datvdemodgui.cpp, plugins/channeltx/moddatv/datvmodgui.ui
For #1136, increase DATV Demod bandwidth max to 50MHz.
=> DATV Demod increase RF bandwidth to 50MHz

plugins/samplesource/limesdrinput/limesdrinputgui.cpp
Fixes a small typo resulting in antennas T2 and T2, rather than T1 and T2.
=> Fix Lime antenna names in GUI combo box

plugins/feature/aprs/aprsgui.ui, plugins/feature/gs232controller/gs232controllergui.ui, plugins/feature/vorlocalizer/vorlocalizergui.ui, sdrgui/CMakeLists.txt, sdrgui/gui/featurelayout.cpp, sdrgui/gui/featurelayout.h, sdrgui/gui/featurewindow.cpp, sdrgui/gui/featurewindow.h, sdrgui/gui/rollupwidget.cpp
This patch adds a QLayout specifically for the Feature window, to try to better use the available space.
I think there are two problems with the current layout used in the Feature windows:
- It doesn't make efficient use of all available space
- Expandable widgets such as the Map, AIS or Radiosonde widgets can't be resized by the user - (the space is just shared equally).
The new FeatureLayout tries to address this, given that the widgets are basically in two categories: Fixed size like AFC, Jogdial, GS232 Controller etc and expandable like Map, AIS, or RadioSonde.
When the layout is set to horizontal, on the left, columns are created with the fixed widgets, then on the right the expandable widgets are placed in a QSplitter, which allows them to be resized. This results in:
This could …
=> Add FeatureLayout - to try to better use space in Feature window

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodadsb/adsbdemodgui.h, plugins/channelrx/demodadsb/readme.md, plugins/feature/map/mapgui.cpp, plugins/feature/map/mapgui.h, plugins/feature/map/mapmodel.cpp, plugins/feature/map/mapsettings.cpp, plugins/feature/map/readme.md
Update station icon on map when My Position preference changes using new signal from #1139 
Also, 2D map uses label rather than name, if available, to be consistent with 3D map.
=> Map/ADS-B: Update station icon on map when My Position preference changes

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodadsb/adsbdemodgui.h, plugins/channelrx/demodadsb/adsbdemodgui.ui, plugins/feature/map/mapgui.cpp, plugins/feature/map/mapgui.h
Remove refresh button as now automatic.
Also fix potential crash when ADS-B or Map GUI is closed.
=> ADS-B: Remove refresh button

plugins/samplesource/sdrplayv3/sdrplayv3input.cpp
According to the API documentation and conversation with SDRplay support, I've implemented what I believe is a proper calculation of final bandwidth in LIF mode. This is only a temporary solution as in my opinion SDRPlayV3 configuration should be organized differently, as current implementation allows to set device in the way it wont work. API docs, mentions only 10 possible configuration of sample ratio, IF bandwidth and IF mode. Quite probably there is at least one more unmentioned and used in SDRuno, but this is under discussion with support.
Closes  #1194
[SDRplay API Specification v3.09](https://www.sdrplay.com/docs/SDRplay_API_Specification_v3.09.pdf)
@srcejon fyi
=> SDRPlayV3: Take LIF downsampling into account when calculating the final bandwidth

sdrgui/channel/channelgui.cpp, sdrgui/device/devicegui.cpp, sdrgui/feature/featuregui.cpp, sdrgui/gui/framelesswindowresizer.cpp, sdrgui/gui/framelesswindowresizer.h, sdrgui/gui/glspectrum.cpp, sdrgui/mainspectrum/mainspectrumgui.cpp
There's currently a small issue with the cursor not being restored after hovering over the border (which changes it to the resize cursor) then being moved immediately over a child widget. In this situation, the FramelessWindowResizer doesn't get a MouseMoveEvent.
This patch fixes this, by enabling mouse tracking on all child widgets.
A small change is also made to GLSpectrum, to enable propagation of MouseMoveEvents to the parent widget.
=> Restore cursor when move from border to child widget

plugins/channelrx/demodais/aisdemodgui.ui, plugins/feature/antennatools/antennatoolsgui.ui, plugins/feature/aprs/aprsgui.cpp, plugins/feature/aprs/aprsgui.ui, plugins/feature/simpleptt/simplepttgui.ui, plugins/samplesource/sdrplayv3/sdrplayv3gui.ui, plugins/samplesource/testsource/testsourcegui.ui, sdrgui/channel/channelgui.h, sdrgui/device/devicegui.h, sdrgui/feature/featuregui.h, sdrgui/gui/workspace.cpp, sdrgui/gui/workspace.h
Add support for auto-stack V6-like window layout as per #1209.
Correct height of bottom bar for ChannelGUI and FeatureGUI from 25 to 22, and DeviceGUI from 25 to 26.
Update size constraints on some windows so they work better with stacked layout.
There are a couple of things I've left for you marked with FIXME in sdrgui/gui/workspace.cpp :)
- Two icons need to be created.
- The state of auto-stacking checkable button should be saved in the application preferences somewhere.
=> V7: Add stack window layout

plugins/channelrx/demodais/readme.md, plugins/channelrx/demodvormc/readme.md, plugins/feature/vorlocalizer/readme.md, plugins/samplemimo/bladerf2mimo/readme.md, plugins/samplesource/limesdrinput/readme.md, plugins/samplesource/xtrxinput/readme.md, sdrgui/readme.md
These are errors that codespell doesn't fix automatically because there is more than one fix.
The following command now gives an empty list of possible fixes, as expected:
find . -name '*.md' -exec codespell --ignore-words-list=cach,doas,ehr,hist,inout,lits,nd,ot,verry --write-changes --summary {} \+
=> Fix typing errors in readme's

devices/usrp/deviceusrp.cpp, devices/usrp/deviceusrpparam.cpp, devices/usrp/deviceusrpparam.h, plugins/samplesink/usrpoutput/readme.md, plugins/samplesink/usrpoutput/usrpoutput.cpp, plugins/samplesink/usrpoutput/usrpoutput.h, plugins/samplesink/usrpoutput/usrpoutputgui.ui, plugins/samplesink/usrpoutput/usrpoutputplugin.cpp, plugins/samplesink/usrpoutput/usrpoutputplugin.h, plugins/samplesource/usrpinput/readme.md, plugins/samplesource/usrpinput/usrpinput.cpp, plugins/samplesource/usrpinput/usrpinput.h, plugins/samplesource/usrpinput/usrpinputgui.ui, plugins/samplesource/usrpinput/usrpinputplugin.cpp, plugins/samplesource/usrpinput/usrpinputplugin.h, sdrgui/deviceuserargs.md
Adds support for non-discoverable (network) USRP devices and user arguments, as per #1159.
I haven't got a network device to test, but as the user arguments work in the same way, it should work.
Also small tweak to USRP device GUI so icons aren't squashed.
=> USRP: Add support for non-discoverable devices and user arguments.

cmake/Modules/CompilerOptions.cmake
This PR disables the NAN and INF optimisations that are enabled by -ffinite-math-only (which is implied by -ffast-math)
This is needed as there are a few bits of code that use NANs (E.g. some code uses NANs to indicate uninitialized variables and then checks with isnan() - however, isnan() doesn't work with -ffinite-math-only) and a few uses of INFINITY too.
I wouldn't expect -ffinite-math-only to make much of a performance difference to the DSP code - but if it does, the option can perhaps be applied more selectively.
=> Disable NAN and INF optimisations on Linux

devices/usrp/deviceusrpparam.cpp
=> USRP: Don't call get_tx/rx methods if tx/rx channels is 0, as may result in KeyError exception

sdrgui/gui/glspectrum.cpp
Currently, if only the spectrum histogram is displayed (i.e. no waterfall), there will be a warning in the log file about an attempt to set a null texture. This is because the waterfall texture height is 0. This patch should remove this warning.
=> Spectrum: Fix null texture warning

sdrgui/gui/glspectrum.cpp
This patch changes the spectrum frequency zoom so that the frequency under the cursor remains the same after the zoom. This makes it easier to zoom in to a particular peak.
Currently, if you zoom using the scroll wheel with the cursor over the peak highlighted in green (i.e. one that isn't at the centre of the spectrum):
the peak will have moved to the right of the cursor after the first zoom increment. If you then zoom again several times without moving the mouse back over the peak, the peak may disappear of the right off the screen.
With this patch, it should stay where it is, relative to the cursor, so you can zoom all the way in to it, without moving the mouse.
=> Change frequency zoom so that frequency under cursor remains the same

sdrgui/gui/spectrummarkersdialog.cpp, sdrgui/gui/spectrummarkersdialog.h
Fix CSV export of show field. Currently limited to 0 or 1, when 0, 1, or 2 are valid values.
Also fixes a small problem in the dialog, where currently the marker name can be lost:
- Create new annotation marker
- Enter a name for the marker - but don't press enter
- Press start button to change to centre
- Marker name is reset
=> Spectrum markers dialog: Small fixes

sdrgui/gui/valuedial.cpp, sdrgui/gui/valuedialz.cpp
If you go in to the Spectrum Markers dialog annotations tab, and really quickly type a value in to the start frequency value dial, if you're fast enough, some of the characters will be lost.
I think the problem is that although the key event handler looks at animation state to see if there's a new value in m_valueNew waiting to update m_value, it is doing that check and update only after it has used m_value - so it can see the old value.
=> Value dial: Check for completed animation before using m_value

sdrgui/gui/glspectrum.cpp
This patch reenables support for zooming using the mouse wheel when cursor is over the waterfall (this was accidentally disabled when adding 3D view)
=> Spectrum: Fix mouse wheel zoom in waterfall

sdrgui/gui/glspectrum.cpp, sdrgui/gui/glspectrum.h, sdrgui/mainspectrum/mainspectrumgui.cpp, sdrgui/mainspectrum/mainspectrumgui.h
This patch allows a user to adjust center frequency up or down in a main spectrum by:
- Holding down the middle mouse button and moving the mouse left or right
- Moving the mouse outside of the spectrum area when dragging a channel marker.
For me, this makes it much quicker and easier to move to frequencies that are just out of range. 
It works quite well on RTL SDR & USRP (for the latter, it's nearly as smooth as moving the channel marker) - but is a little slow on SDRplay.
Note, this works by GLSpectrum emitting a signal requesting a change of center frequency - The change of device frequency is handled by MainSpectrumGUI - so GLSpectrum doesn't need to know whether it is connected to a device or something else.
=> Spectrum: Allow frequency scrolling

sdrbase/dsp/spectrummarkers.h, sdrbase/dsp/spectrumsettings.h, sdrgui/gui/glspectrum.cpp, sdrgui/gui/spectrummarkersdialog.ui
This PR makes two two small changes to spectrum markers.
Firstly, it adds an option of All, to allow both Spectrum markers and Annotations to be displayed at the same time. (MarkersDisplay enum changed to a bitmask in case we want more permutations of additional marker types in the future).
Secondly, it adds an additional option of Text for the Annotation markers, so that the Annotation text is displayed in the header, without the full height bandwidth markers being drawn (just my personal preference!)
Also, I made a small change, so that the bandwidth lines are always drawn when annotations are visible - however, unless the setting is full, the lines are drawn only in the header area, so that you can see where bands start and finish if they are contiguous. If you don't like this, I'm …
=> Spectrum markers: Allow both types to be displayed at the same time

sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/glspectrumgui.h, sdrgui/gui/glspectrumgui.ui, sdrgui/mainspectrum/mainspectrumgui.cpp
Last one :)
This patch adds a combo box to the Spectrum GUI that displays all of the annotation markers - and when pressed, sets the center frequency accordingly, allowing you to quickly jump between pre-defined frequencies.
Combo box is only displayed if there are annotation markers.
=> SpectrumGUI: Add combo box to allow center frequency to be set to marker

sdrgui/gui/valuedial.cpp, sdrgui/gui/valuedialz.cpp
This patch darkens ValueDials when disabled, to make it obvious to the user that they are disabled (i.e. when QWidget::setEnabled(false) is called).
=> Darken ValueDials when disabled

sdrbase/util/ais.cpp
Fix for #1333 
- NMEA sentences must end with CR/LF according to NMEA-0183 specification.
- Don't read beyond end of array.
=> AIS: Terminate NMEA sentences with CR/LF. 

plugins/samplesource/sdrplay/sdrplayinput.cpp
We broke SDRangel with https://github.com/f4exb/libmirisdr-4/commit/fd0452e31264f065bb315e74313384ca4a121ef1
I wasn't expecting any app to actually use the library with that argument in `mirisdr_open`.
Fixes #1340
=> SDRPlayInput: separate HW flavour from mirisdr_open

plugins/channelrx/demoddatv/CMakeLists.txt, plugins/channelrx/demoddatv/datvdemodgui.cpp, plugins/channelrx/demoddatv/datvdemodsettings.cpp, plugins/channelrx/demoddatv/datvdemodsink.cpp, plugins/channelrx/demoddatv/datvdvbs2ldpcdialog.cpp, plugins/channelrx/demoddatv/ldpctool/layered_decoder.h, plugins/channelrx/demoddatv/ldpctool/ldpc_tool.cpp, plugins/channelrx/demoddatv/ldpctool/ldpcworker.cpp, plugins/channelrx/demoddatv/ldpctool/ldpcworker.h, plugins/channelrx/demoddatv/ldpctool/testbench.h, plugins/channelrx/demoddatv/leansdr/dvbs2.h, plugins/channelrx/demoddatv/readme.md
This PR adds support for LDPC on Windows as per #1341. It does this by implementing ldpctool as a Qt worker thread instead of an external process. This can be used on Linux as well, avoiding the need for the ldpctool binary.
However, I've left the lpdctool path in the GUI & settings in case you wanted to make it optional which to use - but it could be removed, if you think this is the way to go. 
I don't really use this plugin, so have only done some basic testing on Linux and Windows. I think there's a DATV demod problem on Windows that can occasionally cause a crash, that isn't related to this change. Needs more investigation though.
=> DATV Demod: Add support for LDPC on Windows

sdrgui/gui/glshadercolormap.cpp, sdrgui/gui/glshaderspectrogram.cpp, sdrgui/gui/glshaderspectrogram.h
Use 2D textures with height 1, instead of 1D textures that aren't available in Open GL ES.
Specify float precision in shaders which seems to be required by ES.
Fix a crash when mutable textures are used.
Should help with #1359
=> Support open GL ES

external/CMakeLists.txt
=> Don't use pkg-config on MacOS when building rtlsdr libraries

modemm17/Correlator.h, plugins/channelrx/demoddatv/datvdemodsink.cpp, plugins/channelrx/demoddatv/ldpctool/layered_decoder.h, plugins/channelrx/demoddatv/leansdr/dvbs2.h
A couple of fixes to M17 and DATV Demod so that it builds on MacOS Mohave.
=> MacOS build fixes

plugins/samplesink/limesdroutput/limesdroutput.cpp, plugins/samplesink/limesdroutput/limesdroutputgui.cpp, plugins/samplesink/limesdroutput/readme.md, plugins/samplesource/limesdrinput/limesdrinput.cpp, plugins/samplesource/limesdrinput/limesdrinputgui.cpp, plugins/samplesource/limesdrinput/readme.md
Handle LMS_Calibrate returning positive error values.
Set Lime minimum frequency in GUI to 30MHz+NCO freq.
Set minimum calibration bandwidth to 2.5MHz.
=> Lime - Partially implement #1389

plugins/samplesource/rtlsdr/rtlsdrgui.cpp, plugins/samplesource/rtlsdr/rtlsdrgui.h, sdrbase/device/deviceapi.cpp, sdrbase/device/deviceapi.h, sdrbase/dsp/dspdevicemimoengine.cpp, sdrbase/dsp/dspdevicemimoengine.h, sdrbase/dsp/dspdevicesinkengine.cpp, sdrbase/dsp/dspdevicesinkengine.h, sdrbase/dsp/dspdevicesourceengine.cpp, sdrbase/dsp/dspdevicesourceengine.h, sdrbase/maincore.h, sdrgui/gui/workspace.cpp, sdrgui/gui/workspace.h, sdrgui/mainwindow.cpp, sdrgui/mainwindow.h
This PR is to primarily add a "start/stop all devices in workspace" button, to the workspace toolbar. 
I find this useful in a couple of cases:
- When recording/playing back data from multiple devices, it helps to sync them in time. (Not perfect, but better than by clicking start individually)
- For some modes, device settings don't need to be adjusted, so the device GUI can be hidden after setup - but start/stop button is still needed. Having it on the toolbar allows device GUI space to be used for something else.
- As with the latency example on the mailing list the other day, it can be useful to stop all devices at the same time to compare spectra.
In order to keep the state / colour of the toolbar button consistent with the state of the devices, I have added a signal in the device API …
=> Add start/stop all devices in workspace button in toolbar. 

plugins/samplesink/limesdroutput/limesdroutput.cpp, plugins/samplesink/limesdroutput/limesdroutput.h, plugins/samplesink/limesdroutput/limesdroutputgui.cpp, plugins/samplesink/limesdroutput/limesdroutputgui.h, plugins/samplesink/limesdroutput/limesdroutputgui.ui, plugins/samplesink/limesdroutput/readme.md, plugins/samplesource/fileinput/fileinputgui.h, plugins/samplesource/limesdrinput/limesdrinput.cpp, plugins/samplesource/limesdrinput/limesdrinput.h, plugins/samplesource/limesdrinput/limesdrinputgui.cpp, plugins/samplesource/limesdrinput/limesdrinputgui.h, plugins/samplesource/limesdrinput/limesdrinputgui.ui, plugins/samplesource/limesdrinput/readme.md
Implements #1389
Indicates calibration errors in GUI via 'C' label. 
Makes LPF BW label background red if setting is not reasonable for up/downconversion using NCO.
Size of device windows tweaked slightly so that the start/stop button isn't squashed.
=> Lime: Implement #1389

app/main.cpp
This PR uses grey text for disabled widgets, which I think makes it a bit clearer that they are disabled.
Example:
=> Use grey text for disabled widgets

sdrgui/gui/workspace.cpp
Small fix to use the full space for spectrum / features when all re-sized channels have been removed from the workspace
=> Stack workspace: Use full width for spectrum when no channels

sdrgui/mainwindow.cpp
Debug builds on Windows are raising an exception on exit, in MainWindow::updateStatus().
This patch stops the status timer in the destructor, so updateStatus() isn't called on deleted objects, which seems to be the problem.
=> Fix crash on exit

plugins/feature/aprs/aprs.cpp
This PR for #1409 enables the APRS Feature to detect Packet Demods in MIMO device sets.
=> #1409 - Detect Packet Demods in MIMO device sets in ARPS Feature

cmake/cpack/CMakeLists.txt
Just reduce the noise during `cmake` run
Resolves `Argument not separated from preceding token by whitespace.` warning.
=> fix cmake syntax warning, separate token by whitespace

plugins/samplesink/limesdroutput/limesdroutputgui.cpp, plugins/samplesource/limesdrinput/limesdrinputgui.cpp
Small fix to Lime GUIs to return a value in all paths through a function.
=> Lime: Add missing return value.

plugins/feature/ais/ais.h, plugins/feature/antennatools/antennatools.h, plugins/feature/aprs/aprs.cpp, plugins/feature/aprs/aprsworker.cpp, plugins/feature/gs232controller/gs232controller.cpp, plugins/feature/gs232controller/gs232controllerworker.cpp, plugins/feature/map/map.h, plugins/feature/pertester/pertester.cpp, plugins/feature/pertester/pertesterworker.cpp, plugins/feature/radiosonde/radiosonde.h, plugins/feature/satellitetracker/satellitetracker.cpp, plugins/feature/satellitetracker/satellitetrackerworker.cpp, plugins/feature/startracker/startracker.cpp, plugins/feature/startracker/startrackerworker.cpp
Call stopWork() from destructor rather than using a slot (which wasn't declared properly) and to ensure order of deletion.
Also delete some dead code.
=> Feature threading cleanup

plugins/feature/map/mapcolordialog.cpp
Workaround Linux bug in color picker in Map feature settings for #1423.
It appears that initial color passed to QColorDialog is lost on Linux if setOptions(QColorDialog::DontUseNativeDialog) is called. So need to call setCurrentColor after setOptions.
=> #1423 - Workaround Linux bug in color picker in map settings

sdrgui/gui/glspectrum.cpp, sdrgui/gui/glspectrum.h
This patch adds the peak power and frequency into the spectrum info bar.
Currently always enabled, but could add a button to make it optional if desired.
=> Spectrum: Add peak power and frequency in info bar

sdrgui/gui/spectrummarkersdialog.ui
The widget name was duplicated, it caused no real issue, sinc it was never referenced, but the UI compiler complained
=> Fix name of widget, it must be unique

plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/channelrx/radioastronomy/radioastronomygui.h, plugins/channelrx/radioastronomy/radioastronomygui.ui, plugins/channelrx/radioastronomy/radioastronomysettings.cpp, plugins/channelrx/radioastronomy/radioastronomysettings.h, plugins/channelrx/radioastronomy/readme.md
In Radio Astronomy plugin, support plotting filtered power series.
Also fixes occasional incorrect display of LAB data.
=> Radio Astronomy: Add filtered power series

sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/glspectrumgui.h, sdrgui/gui/glspectrumgui.ui
This PR adds a button to the spectrum GUI to save the spectrum data to text file
Thoughts? Not a frequently used operation sure, but not sure where else the button could go other than perhaps a popup menu.
=> Spectrum GUI: Add button to save spectrum data to text file

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/feature/satellitetracker/readme.md, plugins/feature/satellitetracker/satellitetrackergui.cpp, plugins/feature/satellitetracker/satellitetrackergui.h, plugins/feature/satellitetracker/satellitetrackerreport.h, plugins/feature/satellitetracker/satellitetrackerworker.cpp, plugins/feature/satellitetracker/satellitetrackerworker.h
In the Satellite Tracker, add variable substitutions for AOS/LOS commands to implement #1452. 
Also add additional variables:
```
${aos}, ${los}, ${elevation}, ${aosAzimuth}, ${losAzimuth}, ${northToSouth}, ${latitude}, ${longitude}, ${altitude}, ${azimuth}, ${elevation}, ${range}, ${rangeRate}, ${speed} and ${period}.
```
Also fixes command splitting for quoted args in this and ADS-B.
=> Satellite Tracker: Add variable substitutions for commands

plugins/channelrx/demodadsb/adsbdemodsettings.cpp, plugins/feature/map/mapsettings.cpp, plugins/feature/vorlocalizer/map/map.qml, plugins/feature/vorlocalizer/vorlocalizergui.cpp, plugins/feature/vorlocalizer/vorlocalizergui.h, plugins/feature/vorlocalizer/vorlocalizersettings.cpp, plugins/feature/vorlocalizer/vorlocalizersettings.h
This patch updates Map feature, ADS-B demod and VOR Feature to use mapboxgl as default map provider on all Linux builds. 
Fix for #1369
=> Maps: Use mapboxgl as default map on Linux,

plugins/channelrx/demodapt/aptdemodgui.cpp, plugins/channelrx/demodapt/aptdemodimageworker.cpp, plugins/channelrx/demodapt/aptdemodsettings.h
Updates to use the latest version of aptdec. This will require rebuilding of aptdec library dependency as the API has changed (as per Linux build instructions).
Removes obsolete zenith variable and adds support for visible image calibration.
Fixes #1422
=> APT Demod: Update to latest aptdec. 

sdrgui/gui/glspectrum.cpp, sdrgui/gui/glspectrum.h, sdrgui/gui/rollupcontents.cpp, sdrgui/gui/rollupwidget.cpp, sdrgui/gui/spectrummeasurements.cpp, sdrgui/gui/spectrummeasurements.h
This patch sizes the spectrum measurements splitter to the size of the measurements table.
This also allows the Auto Stack feature to reduce the width of the spectrum window, when the measurements table is visible.
Also, I've made a change to the RollupWidgets so that they handle Layout Requests from child widgets, which allows the rollups to be resized when a child resizes. Took me a while to find out how to fix this - so there are a few workarounds in other plugins that will be able to be removed (arrangeRollups was being called directly).
=> Spectrum measurements - Size splitter to table

sdrgui/gui/glspectrumview.cpp
At low FFT sizes, it is apparent that the spectrum is not quite aligned with the frequency scale. This is most obvious when peak markers / table are enabled, as the markers don't align with the peaks on the right hand side of the spectrum. (At high FFT sizes, the difference is ~1 pixel, so not visible). But it's also noticeable if you place a marker on a point, and the frequency isn't quite what you'd calculate for the centre of the bin.
This is because the frequency scale goes from -Fs/2/size to Fs/2/size (so size+1 points), but the spectrum line is drawn with size points. The code currently stretches the spectrum over the frequency range, by doing (m_nbBins - 1):
m_glHistogramSpectrumMatrix.scale(
((float) 2 * (width() - m_leftMargin - m_rightMargin)) / ((float) width() * …
=> Align spectrum with frequency scale

plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/feature/satellitetracker/readme.md, plugins/feature/satellitetracker/satellitetrackergui.cpp
Fix #1472 by disabling sorting when adding row to table. Also similar fix in Radio Astronomy plugin.
Fix #1471 by adding missing variables and fixing formatting.
=> Sat tracker: Fix #1472 and #1471

plugins/samplesource/airspy/airspygui.cpp, plugins/samplesource/airspyhf/airspyhfgui.cpp, plugins/samplesource/rtlsdr/rtlsdrgui.cpp, plugins/samplesource/sdrplayv3/sdrplayv3gui.cpp, plugins/samplesource/usrpinput/usrpinputgui.cpp
So most users who don't use the transverter only seem the relevant number of digits for their device, but allow all to be displayed for those who want them.
Just done for a few devices, to see if the patch will be approved. Will follow up with the rest if it is.
=> Adjust number of frequency digits displayed depending whether tranverter is enabled

external/CMakeLists.txt
To fix Mac build, as older tar has been removed, following the new release.
Probably need to switch to alternative method of getting the source in the future, although zlib releases aren't that common.
=> Update zlib to latest version

plugins/feature/satellitetracker/satellitetrackergui.cpp, plugins/feature/satellitetracker/satellitetrackergui.h
=> Sat Tracker: Format time to next event as [HH:]MM:SS, rather than MMMM:SS

plugins/feature/gs232controller/gs232controller.cpp, plugins/feature/gs232controller/gs232controller.h, plugins/feature/gs232controller/gs232controllergui.cpp
For #1484.
Checks for existing pipes, in case Rotator feature is created after selected source channel/feature.
=> Check for existing pipes after GUI is created. 

plugins/channeltx/modatv/atvmodsource.h, sdrbase/dsp/filerecord.cpp, sdrbase/dsp/filerecord.h, sdrbase/dsp/wavfilerecord.cpp, sdrbase/dsp/wavfilerecord.h, sdrgui/mainwindow.cpp
"curent" to "current"
User Visible:
mainwindow.cpp
Function names/Comments:
filerecord.cpp
filerecord.h
wavfilerecord.h
wavfilerecord.cpp
atvmodsource.h
=> Fix recurring typo

plugins/feature/gs232controller/gs232controllerworker.cpp
This patch allows TCP or Serial to be used for any protocol.
=> Rotator controller: Fix support for using Serial or TCP for any protocol

plugins/feature/satellitetracker/satellitetrackergui.cpp
So times with no hours are ahead of times with hours.
=> Satellite Tracker: Fix sorting of next column

sdrgui/gui/glspectrumview.cpp
Implements #1499.
Also fixes array delete operator.
=> 3D spectrum: Allow = as well as + to be used for zoom. 

sdrbase/dsp/spectrumsettings.cpp, sdrbase/dsp/spectrumsettings.h, sdrgui/gui/glshadercolormap.cpp, sdrgui/gui/glshaderspectrogram.cpp, sdrgui/gui/glshadertextured.cpp, sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/glspectrumgui.h, sdrgui/gui/glspectrumgui.ui, sdrgui/gui/glspectrumview.cpp, sdrgui/gui/glspectrumview.h, sdrgui/gui/graphicsviewzoom.cpp, sdrgui/gui/graphicsviewzoom.h, sdrgui/gui/spectrummarkersdialog.ui
Add "show all controls" button, that allows most of the "set once" controls to be hidden on small screens, leaving just one row on my device (may need adjusting for others). Please feel free to make a better icon! Could also be hidden if !ANDROID, if you would prefer not to have it on Linux/Windows.
Add pinch and pan gestures, for frequency scrolling and zooming in to spectrum.
Queue frequencies requested by scrolling, so intermediate frequencies can be omitted, if device is slow to update its frequency.
Support non-integer pixel ratios.  
Add popup sliders for dials.
Add DialogPositioner for dialogs.
Add layout to spectrum markers dialog, so that it can be resized, to fit on smaller screens.
Updates to support some Open GL ES devices.
=> GLSpectrum touchscreen updates

sdrbase/settings/configuration.cpp, sdrbase/settings/configuration.h, sdrgui/channel/channelgui.cpp, sdrgui/channel/channelgui.h, sdrgui/device/devicegui.cpp, sdrgui/device/devicegui.h, sdrgui/feature/featuregui.cpp, sdrgui/feature/featuregui.h, sdrgui/gui/workspace.cpp, sdrgui/gui/workspace.h, sdrgui/mainspectrum/mainspectrumgui.cpp, sdrgui/mainspectrum/mainspectrumgui.h
Add buttons to stack MDI windows vertically and put in tabs.
Use right click to auto-stack sub-windows, rather than having a dedicated button.
Allow maximize button to make window full screen, if already maximized.
Add title to device windows, for when displayed in tabs.
Add menu button to workspace toolbar, for Android only, to avoid having menu bar, which takes up a lot of space.
Add configuration presets button to workspace toolbar. (Will need a following patch to work)
Add icons for window arrangement - please feel free to make some better ones!
=> Window arrangement

plugins/feature/ambe/ambeengine.cpp
Currently the AMBE engine doesn't scan for serial devices on Windows. There the comment:
// Do not activate serial support at all for windows
Any idea why? Bad idea to send commands to all serial devices without knowing what they are?
This PR adds the scanning, which seems to find the device.
=> Scan for serial AMBE devices on Windows

plugins/samplesource/airspy/CMakeLists.txt, plugins/samplesource/airspy/airspyinput.cpp, plugins/samplesource/airspy/airspyplugin.cpp, plugins/samplesource/airspyhf/airspyhfinput.cpp, plugins/samplesource/airspyhf/airspyhfplugin.cpp, plugins/samplesource/audioinput/audioinputplugin.cpp, plugins/samplesource/rtlsdr/CMakeLists.txt, plugins/samplesource/rtlsdr/rtlsdrinput.cpp, plugins/samplesource/rtlsdr/rtlsdrplugin.cpp
On Android, USB devices need to be accessed slightly differently to other OSes.
Device discovery is performed via Android specific code using VID/PID, rather than the device library. Then we have to open devices using a file descriptor, obtained from an Android call.
Similar changes would need to be made to other divers, although the libraries need to have support added for file descriptors.
=> Airspy and RTL SDR support on Android

plugins/feature/satellitetracker/satelliteselectiondialog.cpp
Support relative satellite image URLs as they no longer have http in them.
=> Sat Tracker: Fix satellite images

plugins/samplesource/fileinput/readme.md
The timestamp is is in milliseconds, so make sure people know.
Signed-off-by: rgetz503@gmail.com
=> Update sdriq readme.md

sdrbase/device/deviceenumerator.cpp, sdrbase/device/deviceenumerator.h, sdrgui/gui/samplingdevicedialog.cpp, sdrgui/gui/samplingdevicedialog.h
Device enumeration can take some seconds on Windows, so I've added a progress dialog in the SamplingDeviceDialog.
Also, this dialog no longer automatically refreshes the list of devices, to avoid this potential delay.
=> Add progress dialog for device enumeration, as some drivers are slow on Windows.

plugins/feature/gs232controller/gs232controllerworker.cpp
Fix #1559. Update protocol before calling setAzimuthElevation to avoid wrong protocol for first command.
=> Fix rotator controller protocol setting

plugins/samplesource/audioinput/audioinputgui.cpp, plugins/samplesource/audioinput/audioinputgui.h
If Audio Input device is started without dropdown having been changed, sometimes the audio device will not be opened correctly.
This patch makes sure audio device name corresponds to GUI setting.
It also sets start/stop button background colour according to device status.
=> Audio Input: Make sure audio device name corresponds to GUI setting.

sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/glspectrumgui.h, sdrgui/gui/glspectrumgui.ui
This patch adds a Reset Measurements button to the Spectrum GUI (to reset Mean, Std Dev etc)
Note that the button is only visible when Measurements are enabled.
=> Add reset measurements button to Spectrum GUI

plugins/channelrx/demodft8/ft8demodgui.cpp, plugins/channelrx/demodft8/ft8demodgui.h, plugins/feature/map/mapsettings.cpp
In #1561, you mention adding a feature to collate results and display on a map, but until then, I thought we could just display the callers on the current map direct from the demod, as it's fairly straightforward to do.
=> FT8 Demod: Display caller on Map feature

sdrgui/gui/glspectrumview.cpp
As reported on the mailing list, the channel frequency can disappear if a channel marker is dragged quickly.
This patch prevents that, but not allowing a channel marker to be un-highlighted while a channel is being moved.
=> Spectrum: Keep frequency displayed while channel is being dragged

sdrgui/gui/workspace.cpp, sdrgui/gui/workspace.h
Fix autostack making channel windows too wide when SDRangel starts.
=> Autostack: Fix channel windows being made to wide when SDRangel starts

plugins/channelrx/heatmap/readme.md, sdrbase/maincore.cpp, sdrbase/maincore.h, sdrbase/util/android.cpp, sdrbase/util/android.h, sdrgui/mainwindow.cpp, sdrgui/mainwindow.h
On Android, use a wake lock to prevent app from being put to sleep when devices are running.
Add menu to keep screen on.
=> Android power management

sdrgui/gui/glspectrumview.cpp
Currently, if the MDI area has scroll bars, when zooming in to the spectrum using the mouse wheel, not only will you zoom in, but the MDI area will be scrolled. This fixes that.
=> Prevent MDI scrolling when trying to zoom in on spectrum.

cmake/Modules/CompilerOptions.cmake
So more important ones aren't hidden in the noise.
=> Disable some warnings when compiling with MSVC

plugins/channelrx/demodvor/readme.md, plugins/channelrx/demodvor/vordemod.cpp, plugins/channelrx/demodvor/vordemodgui.cpp, plugins/channelrx/demodvor/vordemodgui.h, plugins/channelrx/demodvor/vordemodgui.ui, plugins/channelrx/demodvor/vordemodsettings.cpp, plugins/channelrx/demodvor/vordemodsettings.h, plugins/channelrx/demodvor/vordemodsink.cpp, plugins/channelrx/demodvor/vordemodsink.h, plugins/channelrx/heatmap/readme.md, swagger/sdrangel/api/swagger/include/VORDemod.yaml, swagger/sdrangel/code/qt5/client/SWGVORDemodSettings.cpp, swagger/sdrangel/code/qt5/client/SWGVORDemodSettings.h
For #1590, this PR improves the filtering of voice over the Morse ident.
It also adds a button in the GUI to enable voice filtering for the audio output.
=> VOR Demod: Improve filtering of voice over Morse ident

plugins/channelrx/demoddsd/dsddemodgui.cpp
Set scope in sink to nullptr before deleting it in the GUI.
Fixes #1617.
=> Fix DSD Demod crash on exit

plugins/feature/vorlocalizer/vorlocalizergui.cpp, plugins/feature/vorlocalizer/vorlocalizergui.h
=> VOR Localizer: Fix updateVORs so it doesn't delete selected VORs. 

plugins/samplesource/testsource/testsourceworker.cpp
On Windows, there can be audio drop outs when using the TestSource. This is because the timer needs to be set to precise before calling start, otherwise it doesn't have an affect.
Just for future reference, there's some code to generate a histogram of timer accuracy in the test source. As the code was, it's all over the place on Windows:
2023-03-08 16:11:40.272 (D) TestSourceWorker::tick: 43: 1
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: 44: 1
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: 45: 1
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: 46: 2
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: 48: 1
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: 50: 1
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: 51: 7
2023-03-08 16:11:40.273 (D) TestSourceWorker::tick: …
=> TestSource: Fix timing on Windows

plugins/channelrx/heatmap/heatmapgui.cpp, plugins/channelrx/heatmap/heatmapgui.ui, plugins/channelrx/heatmap/heatmapsettings.cpp, plugins/channelrx/heatmap/readme.md
Add 10MS/s sample rate, and link bandwidth setting to channel sample rate instead of baseband sample rate.
=> Heat map sample rate

plugins/feature/gs232controller/gs232controllersettings.cpp
Tracking is not working due to a missing setting key. Similar to #1642
=> Add missing setting key in Rotator Controller.

plugins/channelrx/radioastronomy/radioastronomy.cpp, plugins/channelrx/radioastronomy/radioastronomy.h, plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/feature/startracker/startracker.cpp, plugins/feature/startracker/startrackergui.cpp, plugins/feature/startracker/startrackersettings.cpp, plugins/feature/startracker/startrackersettings.h, plugins/feature/startracker/startrackerworker.cpp
This patch fixes a couple of settings keys in the Star Tracker. (Similar to #1642)
It also fixes a few missing connections in the Radio Astronomy plugin and scans for Features when GUI is created.
=> Fix settings keys in Star Tracker and GUI connections in Radio Astronomy

plugins/channelrx/demodnavtex/navtexdemodsink.cpp, plugins/channelrx/heatmap/heatmapgui.cpp, sdrbase/maincore.cpp
Fix compilation with Qt 6.4 - Fixes #1625
Note using Qt 6.5.0 fails to build on Windows due to this Qt bug: https://bugreports.qt.io/browse/QTBUG-112204?jql=text%20~%20%22lconvert%20access%20is%20denied%22
=> Fix Qt6 compilation

plugins/channelrx/demodais/aisdemod.cpp, plugins/channelrx/demodais/aisdemod.h, plugins/channelrx/demodais/aisdemodgui.cpp, plugins/channelrx/demodais/aisdemodgui.h, plugins/channelrx/demodais/aisdemodgui.ui, plugins/channelrx/demodais/aisdemodsettings.h, plugins/channelrx/demodais/aisdemodsink.cpp, plugins/channelrx/demodais/readme.md
This PR addresses a request on the forum to display the time slot used by AIS transmissions.
Note that because SDRangel doesn't currently know the SDR to demod latency, this may not be accurate in terms of absolute slot number.
=> AIS Demod: Calculate time slot used for messages.

.appveyor.yml, CMakeLists.txt, debian/control, plugins/feature/gs232controller/CMakeLists.txt, plugins/feature/gs232controller/gamepadconfigurationdialog.cpp, plugins/feature/gs232controller/gamepadconfigurationdialog.h, plugins/feature/gs232controller/gamepadconfigurationdialog.ui, plugins/feature/gs232controller/gamepadinputcontroller.cpp, plugins/feature/gs232controller/gamepadinputcontroller.h, plugins/feature/gs232controller/gs232controller.cpp, plugins/feature/gs232controller/gs232controllergui.cpp, plugins/feature/gs232controller/gs232controllergui.h, plugins/feature/gs232controller/gs232controllergui.ui, plugins/feature/gs232controller/gs232controllersettings.cpp, plugins/feature/gs232controller/gs232controllersettings.h, plugins/feature/gs232controller/inputcontroller.cpp, plugins/feature/gs232controller/inputcontroller.h, plugins/feature/gs232controller/readme.md, swagger/sdrangel/api/swagger/include/GS232Controller.yaml, swagger/sdrangel/code/qt5/client/SWGGS232ControllerSettings.cpp, swagger/sdrangel/code/qt5/client/SWGGS232ControllerSettings.h
Add support for gamepad/joystick control of the Rotator Controller's target and offset.
This uses Qt Gamepad, and so there are two new package dependencies, libqt5gamepad5-dev and libqt5gamepad5.
I have tried making this optional in CMakeLists.txt, however, it seems on Ubuntu, find_package(qt ... OPTIONAL_COMPONENTS Gamepad) reports an error if the gamepad package isn't installed, rather than just setting the FOUND variable to false.
=> Rotator controller: Add gamepad/joystick control

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodam/amdemodsink.cpp
This PR:
moves the check `> 2.0f` outside of the round brackets to fix an error found with cppcheck:
> Invalid abs() argument nr 1. A non-boolean value is required. [invalidFunctionArgBool]
replace a stray semicolon with a colon to fix a compiler warning:
> warning: label ‘std’ defined but not used [-Wunused-label]
=> Fix cppcheck error and compiler warning

plugins/channelrx/demoddab/readme.md, plugins/channelrx/demodft8/readme.md, plugins/channelrx/demodils/readme.md, plugins/channelrx/demodnavtex/readme.md, plugins/channelrx/heatmap/readme.md
Fixed with:
find . -name '*.md' -exec codespell --ignore-words-list=cach,doas,ehr,inout,lits,nd,verry --summary --write-changes {} \+
and then running the same command with --interactive=2: find . -name '*.md' -exec codespell --ignore-words-list=cach,doas,ehr,inout,lits,nd,verry --summary --write-changes --interactive=2 {} \+
=> Fix spelling

app/main.cpp, appbench/main.cpp, appsrv/main.cpp
Fixes errors found by cppcheck:
app/main.cpp:149:10: error: Unmatched '('. Configuration: ''. [syntaxError]
appsrv/main.cpp:85:10: error: Unmatched '('. Configuration: ''. [syntaxError]
appbench/main.cpp:88:10: error: Unmatched '('. Configuration: ''. [syntaxError]
=> Remove extra open round brackets

plugins/channelrx/demodapt/aptdemodgui.cpp, plugins/channelrx/demodapt/aptdemodsettingsdialog.cpp, plugins/channelrx/heatmap/heatmapgui.cpp, plugins/channelrx/radioastronomy/radioastronomygui.cpp
Filter needs to be space separated, not semicolon separated.
Fixes #1681.
=> Fix QFileDialog filters to work with non-native file dialog.

plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/channelrx/radioastronomy/radioastronomygui.h, plugins/feature/gs232controller/gs232controllergui.ui, plugins/feature/gs232controller/rotctrldprotocol.cpp, plugins/feature/satellitetracker/satellitetrackerworker.cpp, plugins/feature/startracker/readme.md, plugins/feature/startracker/startracker.cpp, plugins/feature/startracker/startracker.h, plugins/feature/startracker/startrackergui.cpp, plugins/feature/startracker/startrackergui.h, plugins/feature/startracker/startrackergui.ui, plugins/feature/startracker/startrackersettings.cpp, plugins/feature/startracker/startrackersettings.h, plugins/feature/startracker/startrackerworker.cpp, sdrgui/gui/decimaldelegate.h
Just a bit too late... Fix Sat Tracker crash introduced by last patch for #1682.
Add support for tracking Satellites in the Star Tracker, to enable satellites to be used as calibration signals in Radio Astronomy plugin.
=> Fix Sat Tracker crash

sdrgui/gui/samplingdevicedialog.cpp, sdrgui/gui/samplingdevicedialog.h
In Sampling Device Dialog, only update widgets from UI thread. May fix #1692.
=> Sampling Device Dialog. Only update widgets from UI thread.

plugins/samplesink/plutosdroutput/plutosdroutput.cpp
For #1690, this adds a few additional settings keys that look like they are missing (they are in the Pluto Input which supposedly works - you need to see a little more context that what the github diff shows).
I don't have a Pluto, so can't test( but this PR should create a build other people can try).
=> Add missing settings keys for Pluto Output. 

plugins/feature/gs232controller/gs232controllergui.cpp, plugins/feature/gs232controller/gs232controllergui.h, plugins/feature/gs232controller/gs232controllergui.ui, plugins/feature/gs232controller/gs232controllersettings.cpp, plugins/feature/gs232controller/gs232controllersettings.h, swagger/sdrangel/api/swagger/include/GS232Controller.yaml, swagger/sdrangel/code/qt5/client/SWGGS232ControllerSettings.cpp, swagger/sdrangel/code/qt5/client/SWGGS232ControllerSettings.h
=> Rotator Controller: Use floats for az/el offsets. 

external/CMakeLists.txt
Switches codec2 repo from codec2 to codec2-dev to access the v1.0.3 tag.
Eventually, we should switch back and upgrade to the latest (which may not be straight forward to get the Windows build working), but this is a quick fix for the Mac build.
For #1741.
=> Switch to codec2-dev repo to access v1.0.3 tag. 

external/CMakeLists.txt
Fix misspelling of FFMPEG_FOUND in external/CMakeLists.txt, noticed while reviewing the logs for #1740
=> Fix misspelling of FFMPEG_FOUND

cmake/ci/build_sdrangel.sh, debian/rules
Use == instead of = for comparison in cmake/ci/build_sdrangel.sh 
Remove external projects (libsigmf) from .deb.
=> Fix syntax error in cmake/ci/build_sdrangel.sh and remote external files from .deb

plugins/feature/gs232controller/CMakeLists.txt, plugins/feature/gs232controller/gamepadconfigurationdialog.cpp, plugins/feature/gs232controller/gamepadconfigurationdialog.ui, plugins/feature/gs232controller/gamepadinputcontroller.cpp, plugins/feature/gs232controller/gamepadinputcontroller.h, plugins/feature/gs232controller/gs232controller.cpp, plugins/feature/gs232controller/gs232controllergui.cpp, plugins/feature/gs232controller/gs232controllergui.h, plugins/feature/gs232controller/gs232controllergui.ui, plugins/feature/gs232controller/gs232controllerplugin.cpp, plugins/feature/gs232controller/gs232controllersettings.cpp, plugins/feature/gs232controller/gs232controllersettings.h, plugins/feature/gs232controller/inputcontroller.cpp, plugins/feature/gs232controller/inputcontroller.h, plugins/feature/gs232controller/inputcontrollersettings.h, plugins/feature/gs232controller/readme.md, sdrgui/CMakeLists.txt, sdrgui/gui/loglabelslider.cpp, sdrgui/gui/loglabelslider.h, sdrgui/gui/logslider.cpp, sdrgui/gui/logslider.h
This patch adds some additional calibration to the gamepads in the Rotator Controller Feature: 
- Support for deadzones, 
- higher precision sensitivity setting using a logarithmic slider
- ability to switch between high and low sensitivity setting for coarse or fine targetting
Also, some functions of the Rotator Controller can now be controlled by gamepad buttons (Start/stop controller, enable tracking, toggle sensitivity mode)
=> Rotator controller: Additional gamepad calibration

CMakeLists.txt, app/main.cpp, plugins/feature/map/CMakeLists.txt, plugins/feature/map/map.qrc, plugins/feature/map/map/ModifiedMapView.qml, plugins/feature/map/map/map_6.qml, plugins/feature/map/mapgui.cpp, plugins/feature/map/mapgui.h, plugins/feature/map/mapitem.cpp, plugins/feature/map/mapplugin.cpp, plugins/feature/map/mapsettings.cpp, plugins/feature/map/mapsettingsdialog.cpp, plugins/feature/map/osmtemplateserver.h, plugins/feature/map/webserver.cpp, sdrbase/util/osndb.cpp
Qt 6.5 now supports Qt location, so this PR updates the map to work with it.
Also some fixes for Qt 6.6
=> Support Map plugin for Qt 6.5. 

plugins/feature/gs232controller/gs232controllergui.cpp
Code provided by srcejon, tested by lrowen locally for proper operation.
=> Use precision to control single-step size in gs232controller feature [Issue# 1771]

plugins/feature/map/ibpbeacon.cpp
This PR updates some callsigns and some  locators according to the information currently at https://www.ncdxf.org/beacon/beaconlocations.html
=> Update callsigns and locators of IBP beacons

sdrbase/CMakeLists.txt, sdrbase/device/deviceapi.cpp, sdrbase/device/deviceapi.h, sdrbase/maincore.h, sdrbase/settings/mainsettings.cpp, sdrbase/settings/mainsettings.h, sdrbase/settings/pluginpreset.cpp, sdrbase/settings/pluginpreset.h, sdrbase/settings/serializableinterface.h, sdrgui/CMakeLists.txt, sdrgui/channel/channelgui.h, sdrgui/device/devicegui.h, sdrgui/device/deviceuiset.cpp, sdrgui/device/deviceuiset.h, sdrgui/feature/featuregui.h, sdrgui/gui/basicchannelsettingsdialog.cpp, sdrgui/gui/basicchannelsettingsdialog.h, sdrgui/gui/basicchannelsettingsdialog.ui, sdrgui/gui/basicdevicesettingsdialog.cpp, sdrgui/gui/basicdevicesettingsdialog.h, sdrgui/gui/basicdevicesettingsdialog.ui, sdrgui/gui/basicfeaturesettingsdialog.cpp, sdrgui/gui/basicfeaturesettingsdialog.h, sdrgui/gui/basicfeaturesettingsdialog.ui, sdrgui/gui/pluginpresetsdialog.cpp, sdrgui/gui/pluginpresetsdialog.h, sdrgui/gui/pluginpresetsdialog.ui, sdrgui/mainwindow.cpp, sdrgui/mainwindow.h
This PR adds support for Plugin Presets (or Device/Channel/Feature Presets), as discussed a while back in #1430.
This allows Presets to be saved / loaded for individual Devices, Channels and Features, via the new Star button in the basic settings dialog. E.g:
It should basically work the same as the existing Device Set and Feature Set presets, except that the preset only applies to a single Device, Channel or Feature.
If a preset is saved with Group/Description as Defaults/Default, then it will be loaded automatically whenever a plugin of that particular type is created.
=> Add support for Plugin Presets

external/CMakeLists.txt, plugins/samplesource/rtlsdr/rtlsdrgui.cpp, plugins/samplesource/rtlsdr/rtlsdrgui.ui, plugins/samplesource/rtlsdr/rtlsdrinput.cpp, plugins/samplesource/rtlsdr/rtlsdrinput.h
I noticed two problems with Nooelec RTLSDR with E4000 tuner:
- Gain setting was not working. After adjusting the gain, it would re-adjust itself as though AGC had been reenabled. It appears we need to call rtlsdr_set_tuner_gain_mode before each call to rtlsdr_set_tuner_gain.
- Adjusting RFBW would result in a bizarre frequency response.
Also, added a change to the GUI that displays the tuner type and disables Ofs checkbox if not supported for the given tuner.
=> Fix RTLSDR E4000 gain and bandwidth settings and add RTLSDRBlog V4 support

plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/channelrx/radioastronomy/radioastronomygui.h, plugins/channelrx/radioastronomy/radioastronomygui.ui, plugins/channelrx/radioastronomy/radioastronomysettings.h, plugins/channelrx/radioastronomy/readme.md, plugins/feature/startracker/startrackergui.cpp, plugins/feature/startracker/startrackergui.h, plugins/feature/startracker/startrackerworker.cpp, sdrbase/channel/channelwebapiutils.h
In the Radio Astronomy, add rotator Az/El and az/el offset to table.
Also optimizes redrawing of charts in the Star Tracker, as was being redrawn unnecessarily and unnecessary refraction calculation was very slow.
=> Radio Astronomy: Add rotator Az/El and offset to table

plugins/feature/map/mapbeacondialog.cpp, plugins/feature/map/mapradiotimedialog.cpp
Some columns of the Beacons and of the Radio Time tables where sorted as strings; for example, in the following image, 162 is sorted before 40. but it should be sorted after 77.5.
This PR uses the same code used for the Distance columns to call `setData()` with numeric variables instead  of strings.
This code cona't be used for the Frequency column of the Beacons table because the cells contain the frequency and the unit as string.
=> Fix sorting of numeric columns

plugins/channelrx/demodpager/pagerdemodgui.cpp, sdrbase/dsp/phasediscri.h
This PR initialises state in the PhaseDiscriminators class, to prevent it from randomly outputting huge values (ie. 1e+30).
(When such a large value gets in to the MovingAverageUtil, it will stay there, as it keeps a running total, rather than resumming the elements. 1e30-1=1e30)
This fixes #1794.
Patch also connects scope signals in Pager demod, noticed while debugging this issue.
=> Initialise PhaseDiscriminators state, to avoid outputting huge values.

app/main.cpp, appsrv/main.cpp, sdrbase/CMakeLists.txt, sdrbase/mainparser.cpp, sdrbase/mainparser.h, sdrbase/remotetcpsinkstarter.cpp, sdrbase/remotetcpsinkstarter.h
The following patch adds command line options to be able to start the Remote TCP Sink on a specified device, so you can start a remote server without using the API or GUI, which should hopefully make it easier to use. E.g:
sdrangelsrv --remote-tcp --remote-tcp-hwtype RTLSDR
Additional options:
--remote-tcp-serial: Specify device by serial number, instead of a hwtype
--remote-tcp-address: TCP address of interface to listen on
--remote-tcp-port: TCP port to listen on
--list-devices: List physical devices, so you can see what needs to be passed to --remote-tcp-hwtype/serial
All the device settings (sample rate / freq etc) can be set by the client Remote TCP Device GUI, so shouldn't need command line options.
Thoughts?
=> Command line options to start Remote TCP Sink

sdrbase/util/osndb.cpp
=> Distinguish between China and Taiwan aircraft registrations in ADS-B Demod

CMakePresets.json
This PR updates CMakePresets.json to add a windows-default preset, that can be used to configure and build SDRangel easily from within Visual Studio (Just need to open the folder and hit build).
Hopefully Linux presets should remain the same. Have just added an option that indicates they are for Linux, so VS doesn't try to build them.
=> Add windows-default CMake preset for building with Visual Studio

CMakeLists.txt, external/CMakeLists.txt, plugins/channelrx/demoddatv/CMakeLists.txt, plugins/channeltx/modatv/CMakeLists.txt, plugins/channeltx/moddatv/CMakeLists.txt
Enable C language, as needed for some external projects.
Fix ffmpeg/opencv dependencies, to avoid error when cmake is run for a second time.
=> Fixes for Mac build

plugins/channelrx/demodpager/pagerdemod.cpp
In Pager demod, flush log stream so data is available immediately. For #1833.
=> Pager: Flush log stream after write, so data is available immediately

swagger/sdrangel/examples/Readme.md
Hello!
It looks like the `ptt_active.py` was moved to the `scriptsapi` directory and [was renamed to `ptt_feature.py`](https://github.com/f4exb/sdrangel/commit/52e20382c05e78aef3ac0618d91ada9bf81c493d). I am proposing removing the obsolete description in `swagger/sdrangel/examples/Readme.md`.
Let me know if you have any feedback, thanks!
=> Remove `ptt_active.py` section

.github/workflows/sdrangel.yml
As brew complains about 11 being unsupported and fails
=> Update github action to use MacOS 12

plugins/channelrx/demodais/aisdemodbaseband.cpp, plugins/channelrx/demodais/aisdemodgui.cpp, plugins/channelrx/demoddsc/dscdemodbaseband.cpp, plugins/channelrx/demoddsc/dscdemodbaseband.h, plugins/channelrx/demoddsc/dscdemodgui.cpp, plugins/channelrx/demoddsc/dscdemodsink.cpp, plugins/channelrx/demoddsc/dscdemodsink.h, plugins/channelrx/demodnavtex/navtexdemodbaseband.cpp, plugins/channelrx/demodnavtex/navtexdemodbaseband.h, plugins/channelrx/demodrtty/rttydemodbaseband.cpp, plugins/channelrx/demodrtty/rttydemodbaseband.h, plugins/channelrx/radioclock/radioclockbaseband.cpp, plugins/channelrx/radioclock/radioclockgui.cpp
This PR fixes 2 race conditions in some RX demods.
The first is the initialisation of the number of streams used by a scope. Currently this is performed in the GUI, but this can be too slow, if the sink gets samples before the GUI initialisation code has run, resulting in a crash. So I've moved the init code to the baseband, where the scope is created. 
The next problem appears if a channel is added to a device set that is already running. When this happens, the baseband class initially receives a DSP signal notification with a baseband sample rate of 0. This results in the DownChannelizer not being initialised properly. For some demods with low sample rates, it seems Baseband::handleData() can be called before the correct baseband sample rate is received and used to correctly initialise …
=> Fix 2 race conditions

sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/glspectrumview.cpp
Unintentionally removed some implicit typecasting with my previous commit. Here I add them back explicitly.
=> Add explicit typecasting that was missing

plugins/channeltx/modpsk31/psk31modbaseband.cpp, plugins/channeltx/modrtty/rttymodbaseband.cpp
Use channel sample rate of 48k in RTTY and PSK31 mods to reduce filter taps at high baseband sample rates.
Partially helps with #1862, but need to rewrite RaisedCosine filter normalisation code when I get some time.
=> Use channel sample rate of 48k in RTTY and PSK31 mods

.github/workflows/sdrangel.yml, plugins/channelrx/demodam/amdemod.cpp, plugins/channelrx/demodam/amdemodgui.cpp, plugins/channelrx/demodam/amdemodgui.h, plugins/channelrx/demodam/amdemodgui.ui, plugins/channelrx/demodam/amdemodsettings.cpp, plugins/channelrx/demodam/amdemodsettings.h, plugins/channelrx/demodam/readme.md, sdrgui/channel/channelgui.cpp, sdrgui/gui/valuedialz.cpp, swagger/sdrangel/api/swagger/include/AMDemod.yaml, swagger/sdrangel/code/qt5/client/SWGAMDemodSettings.cpp, swagger/sdrangel/code/qt5/client/SWGAMDemodSettings.h
Currently AM Demod channel center frequency is specified by Δf setting. This PR adds a couple of additional modes, that are selected by a combo box that replaces the Δf label:
Δf option uses current behaviour
25k - Allows entry of an absolute frequency specified in MHz (as is typical in the airband). This I think has two advantages:
- No need for any mental arithmetic - you can just type in the ATC frequency you are interested in.
- The demod stays locked to that frequency, even if the device center frequency changes. (So, you can make adjustments to the device center frequency, without needing to manually retune the demod)
The valuedial only displays 6 digits, as this is typically how airband frequencies are specified / spoken. Although not normally needed with AM, it's still possible to …
=> AM Demod: Add additional modes to specify channel center frequency

plugins/channelrx/demodradiosonde/radiosondedemod.cpp, plugins/channelrx/demodradiosonde/radiosondedemodgui.cpp, plugins/channelrx/demodradiosonde/radiosondedemodgui.h, plugins/channelrx/demodradiosonde/radiosondedemodgui.ui, plugins/channelrx/demodradiosonde/radiosondedemodsettings.h, plugins/channelrx/demodradiosonde/readme.md
For #1880 
Add altitude, speed and heading to log file.
Add range and frequency columns to table.
=> Radiosonde updates for #1880

plugins/channelrx/demodam/amdemodgui.cpp, plugins/channelrx/demodbfm/bfmdemodgui.cpp, plugins/channelrx/demoddab/dabdemodgui.cpp, plugins/channelrx/demoddatv/datvdemodgui.cpp, plugins/channelrx/demoddsd/dsddemod.cpp, plugins/channelrx/demoddsd/dsddemod.h, plugins/channelrx/demoddsd/dsddemodgui.cpp, plugins/channelrx/demoddsd/dsddemodgui.ui, plugins/channelrx/demodfreedv/freedvdemodgui.cpp, plugins/channelrx/demodft8/ft8demodgui.cpp, plugins/channelrx/demodils/ilsdemodgui.cpp, plugins/channelrx/demodm17/m17demodgui.cpp, plugins/channelrx/demodnfm/nfmdemodgui.cpp, plugins/channelrx/demodssb/ssbdemodgui.cpp, plugins/channelrx/demodvor/vordemodgui.cpp, plugins/channelrx/demodvormc/vordemodmcgui.cpp, plugins/channelrx/demodwfm/wfmdemodgui.cpp, plugins/channelrx/freqtracker/freqtrackergui.cpp, plugins/channeltx/modam/ammodgui.cpp, plugins/channeltx/modfreedv/freedvmodgui.cpp, plugins/channeltx/modm17/m17modgui.cpp, plugins/channeltx/modnfm/nfmmodgui.cpp, plugins/channeltx/modssb/ssbmodgui.cpp, plugins/channeltx/modwfm/wfmmodgui.cpp, plugins/samplemimo/audiocatsiso/audiocatsisogui.cpp, plugins/samplesink/audiooutput/audiooutputgui.cpp
DSD Demod constellation will not appear if !m_running when GUI is created or if acquisition is restarted (which recreates the baseband object).
This patch fixes this, by saving a pointer to m_scopeXYSink in DSDDemod, so that it can be used to initialise the baseband/sink every time it is created.
Also, this patch adds a warning in the DSDDemod GUI if the sample rate is < 48kHz.
For #1836
=> DSD Demod - Fix loss of constellation

plugins/channelrx/remotetcpsink/remotetcpsinksink.cpp, plugins/samplesource/remotetcpinput/remotetcpinputtcphandler.cpp
For #1885, in Remote TCP Input, fix FIFO size adjustment, so sample rates >3MS/s work. 
Also, in Remote TCP Input, when RTL0 protocol is used, match channel sample rate to device sample rate.
=> Remote TCP - Fix FIFO size adjustment, so sample rates >3MS/s work. 

plugins/channelrx/demodwfm/wfmdemod.h, plugins/channelrx/demodwfm/wfmdemodbaseband.cpp, plugins/channelrx/demodwfm/wfmdemodbaseband.h, plugins/channelrx/demodwfm/wfmdemodgui.cpp, plugins/channelrx/demodwfm/wfmdemodgui.h, sdrbase/audio/audiofifo.h, sdrbase/audio/audiooutputdevice.cpp
Currently, there appears to be no indication if audio underflow occurs. There's a message in the log if overflow occurs.
This PR indicates if overflow/underflow has occurred in the last second, by setting the background of the audio mute button to yellow.
Currently the patch is just for WFM Demod - but if you think this is the way to go, I can add to other demods.
Although much of the time underflows are inaudible (to my ears at least), I think it's useful to indicate there's a problem for when audio is being piped to an external demod, as it may be more problematic. (Good example of when they occur, is with some RTL SDRs running at 3.2MSa/s - as not all can quite do it).
The patch also changes how the audio output device works slightly, to try to avoid some zero padding. Currently, the …
=> Indicate audio FIFO underflow/overflow in GUI

sdrgui/gui/tabletapandhold.cpp
Sometimes a table's popup menu can appear when scrolling a table, due to the tapAndHold gesture. This PR should fix it.
=> Prevent popup menu when scrolling tables

sdrgui/CMakeLists.txt, sdrgui/device/deviceuiset.cpp, sdrgui/feature/featureuiset.cpp, sdrgui/gui/mdiutils.cpp, sdrgui/gui/mdiutils.h, sdrgui/mainwindow.cpp
For #1835, this PR should fix MDI window positions/size when multiple monitors are available, and also should fix the small vertical offset I see on Linux.
Seems to be an improvement on both Linux and Windows for me, but let me know if there's still any problems.
=> Fix MDI window geometry save/restore

modemm17/M17Modulator.h, plugins/channelrx/demodm17/m17demodprocessor.cpp
For #1826, reverse byte ordering of CRC in packet mode in M17 modem
=> Reverse byte ordering of CRC in packet mode in M17 modem

modemm17/M17Modulator.h, plugins/channelrx/demodm17/m17demodprocessor.cpp, plugins/channeltx/modm17/m17modprocessor.cpp, sdrgui/gui/mdiutils.cpp
=> M17: Update packet format to comply with current spec

plugins/channelrx/demodm17/m17demod.cpp, plugins/channelrx/demodm17/m17demod.h, plugins/channelrx/demodm17/m17demodgui.cpp, plugins/channelrx/demodm17/m17demodgui.ui, plugins/channelrx/demodm17/m17demodprocessor.cpp, plugins/channelrx/demodm17/m17demodsettings.cpp, plugins/channelrx/demodm17/m17demodsink.cpp, plugins/channeltx/modm17/m17modgui.cpp, plugins/channeltx/modm17/m17modsettings.cpp, plugins/channeltx/modm17/m17modsource.cpp
Fix M17 packet decoding - bit indices were being used in to a byte array, as mentioned in #1892.
Also remove copy+paste error in GUI tooltip.
=> Fix M17 packet type decoding.

plugins/channelrx/demodadsb/adsbdemoddisplaydialog.ui
Fix #1896 - Split widgets in to 2 tabs, so it can fit on small Android screens
=> Update layout of ADS-B Display Settings Dialog to support small screens

sdrbase/dsp/scopevis.cpp
This is a possible fix for #1901, but please review
Currently, the code in processTrace only ever appears to look at the first sample in a block of data
const Complex& s = *vbegin[triggerStreamIndex];
I'm guessing it needs to be indexed using processed (as that variable isn't read anywhere else in the loop)
const Complex& s = vbegin[triggerStreamIndex][processed];
And it seems to trigger more as I'd expect.
=> Attempt to fix scope trigger

.github/workflows/sdrangel.yml, plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/freqscanner/freqscanner.cpp, plugins/channelrx/freqscanner/freqscanner.h, plugins/channelrx/freqscanner/freqscannergui.cpp, plugins/channelrx/radioastronomy/radioastronomy.cpp, plugins/channelrx/radioastronomy/radioastronomy.h, plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/feature/map/map/map.qml, plugins/feature/map/map/map_6.qml, plugins/feature/map/mapgui.cpp, plugins/feature/map/mapitem.cpp, plugins/feature/map/mapitem.h, plugins/feature/map/mapmodel.cpp, plugins/feature/map/mapmodel.h, plugins/feature/map/mapsettings.cpp, plugins/feature/map/mapsettingsdialog.ui, plugins/feature/startracker/startrackerworker.cpp, sdrbase/channel/channelwebapiutils.cpp, sdrbase/maincore.cpp, sdrbase/maincore.h, sdrgui/mainwindow.cpp
As requested on the [forum](http://sdrangel.org/forum/viewtopic.php?t=134), this PR updates the Map popup menu to allow specifying which device to tune to the specified frequency and also adds support for tuning all frequencies related to the map item, not just the first.
Also, the the maplibre plugin has been renamed maplibregl to match the latest release.
In implementing the above, I also tried to consolidate some of the code in various plugins that deals with Device and Channel Ids (E.g. R0:3). For the time being, I added some code in MainCore for this, but I will open another issue with a few problems it has.
=> Map: Support multiple frequencies and specify which device to tune

.github/workflows/sdrangel.yml, plugins/channelrx/demodradiosonde/radiosondedemod.cpp, plugins/samplesource/sdrplayv3/CMakeLists.txt
Fix radiosonde CSV header - for #1915.
Also updates SDRplay library path on Mac, to support API 3.12.1.
=> Radiosonde CSV header fix

plugins/samplesource/fileinput/fileinputgui.cpp
In File Input plugin, start file browser in directory containing last selected file, so you don't have to keep on browsing through lots of directories to get to other files in the same directory.
=> File Input: Start file browser in directory of last file selected.

external/CMakeLists.txt
The external library LAME (v3.100) frontend binaries fail to build (https://github.com/f4exb/sdrangel/issues/1933) on MacOS currently with:
```log
parse.c:417:34: error: call to undeclared function 'id3tag_set_comment_ucs2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```
We dont need the LAME frontend binaries themselves, only the shared library, so we can disable their build and avoid this bug in their current code.
=> Disable build of LAME frontend

plugins/channelrx/demodpager/pagerdemod.cpp
For #1936 - Use separate date/time fields and prefix address with leading 0 so always 7 chars.
=> Pager UDP packet update

sdrbase/webapi/webapirequestmapper.cpp
Editing FrequencyScanner via api endpoint cases application crash to access by null pointer.  
Failure happens when swagger generated setValue method is called for complex/nested structure on the object with is created purely by constructor, but not initialised by the ::init method.
Solution:
1. Call init on newly created object
2. Proactively fix this for all types of settings objects
This change addresses https://github.com/f4exb/sdrangel/issues/1951
=> fix SIGSEGV on /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings endpoint

plugins/feature/simpleptt/simplepttgui.cpp, plugins/feature/simpleptt/simplepttworker.cpp
- Fix misuse of device index
- Add "None" option to SimplePTT to disable partial Rx/Tx switching
- Support MIMO device
=> SimplePTT: bugfix and enhancement

devices/limesdr/devicelimesdr.cpp, devices/limesdr/devicelimesdrparam.cpp, devices/limesdr/devicelimesdrparam.h, sdrbase/device/deviceenumerator.cpp, sdrbase/device/deviceenumerator.h, sdrbase/plugin/pluginmanager.cpp
- Rewrite **_enumerateDevices_**: support to enumerate all devices in one call
- Add **_enumerateAllDevices_** to reduce startup period
- Optimize LimeSDR enumerating by skipping LMS_Init
i have tested it on LimeSDR for all sinks, sources and MIMOs.
it's my first complicated PR, so please feel free to advise or edit.
=> Optimize eumerator of origin device

sdrbase/device/deviceapi.cpp, sdrbase/device/deviceapi.h, sdrgui/mainwindow.cpp, sdrsrv/mainserver.cpp
fix _clearBuddiesLists_ only calls _removeSinkBuddy_, missing source buddies.
additionally:
- merge _addSinkBuddy_ and _addSourceBuddy_ into _addBuddy_.
- merge _removeSinkBuddy_ and _removeSourceBuddy_ into _removeBuddy_.
- both functions mentioned above are dispatched by _DeviceAPI.m_streamType_
=> Fix not remove source buddy

sdrbase/dsp/spectrumvis.cpp, sdrbase/dsp/spectrumvis.h
Use log2 approximation to increase performance of spectrum power calculation. 
As discussed in #2004
=> Use log2 approximation in spectrum power calculation

sdrbase/dsp/vkfftengine.cpp
just noticed during compilation. Not a big issue, but better to fix, to not have some potential garbage in variables which are not set explicitly.
=> fix memset() arguments order in vkfftengine

cmake/cpack/deploy_mac.cmake.in
On mac, fix missing QML libs, by scanning all plugins, not just the map. For #2010
=> Mac: Scan all plugins for qml

snap/local/locale-gen, snap/local/sdrangel_wrapper.sh, snap/snapcraft.yaml
This patch updates the snap script to build the latest version of SDRangel and include additional drivers.
I recently saw someone trying to install it from the snap store, and it didn't work on recent versions of Ubuntu and is only version 5 with Lime support. Also, I notice if you just type sdrangel on an Ubuntu machine, it will recommend to install it from the snap store.
Not really a fan of the sandboxing, but may as well give users who try it the best experience. I've tried the snap it builds and it works on Ubuntu 18.04 and 23.10, and Fedora 39, so does at least give a way of running a single binary on a range of distributions.
I guess you'd need to do a build and push it to the store.
Users need to give USB permissions with:
sudo snap connect sdrangel:raw-usb
There's a check for …
=> Snap update

plugins/channelrx/demodadsb/CMakeLists.txt, plugins/channelrx/demodadsb/adsbdemoddisplaydialog.cpp, plugins/channelrx/demodadsb/adsbdemodgui.cpp, sdrgui/gui/crightclickenabler.cpp
Prevent dialogs from being opened twice on Linux and Mac when right clicking. Partially fixes #1979
Hide ADS-B maps that aren't available. For #2010
=> 2 Bug Fixes

plugins/channelrx/channelpower/channelpowergui.cpp, sdrbase/util/db.h
As Airspy HF+ can operate in this region. Fixes #2020
=> Decrease default floor in Db calculation from -120dB to -150dB

plugins/samplesource/audioinput/audioinputgui.cpp, plugins/samplesource/fcdpro/fcdproinput.cpp, plugins/samplesource/fcdproplus/fcdproplusinput.cpp, sdrbase/audio/audiodeviceinfo.cpp, sdrbase/audio/audiodeviceinfo.h, sdrbase/audio/audiodevicemanager.cpp, sdrbase/audio/audiodevicemanager.h, sdrbase/audio/audiooutputdevice.cpp, sdrbase/webapi/webapiadapter.cpp, sdrgui/gui/audiodialog.cpp, sdrgui/gui/audioselectdialog.cpp
Makes every **AudioDeviceInfo** singleton to reduce QAudioDeviceInfo calls. frequently calling WASAPI enumerate when startup will lead to crash on my PC... not really know why but it's an optimization anyway.
Fix things about `m_defaultInputStarted `and `m_defaultOutputStarted`. It creates default devices multiple times, causing totally broken and noncontinuous audio.
=> Audio optimize & default input/output bugfix

plugins/feature/sid/sidaddchannelsdialog.cpp
This PR makes the columns in the "Add Channels" dialog of the SID plugin and aligns the cells of the frequency to the right. The headers of the columns with the checkboxes are clickable but they all have the same value irrespective of the checked state, so clicking on their header doesn't change the sorting.
=> [SIDAddChannelsDialog] Make columns sortable

plugins/feature/CMakeLists.txt
When Qt Location is not available, cmake prints
```
-- Not building map (ENABLE_FEATURE_MAP=ON Qt6Quick_FOUND=1 Qt6QuickWidgets_FOUND=1 Qt6Positioning_FOUND=1 Qt6Location_FOUND=0)
[...]
CMake Error at plugins/feature/skymap/CMakeLists.txt:74 (target_link_libraries):
Target "featureskymap" links to:
Qt::Location
but the target was not found.  Possible reasons include:
```
(I'm using Debian testing and at this time in not yet available for Qt 6, it's available in experimental.
The existing test was wrong in the part that checked for WebEngine/WebEngineCore the because precedence is from left to right (https://cmake.org/cmake/help/latest/command/if.html#and) and it didn't check for Qt Location.
In the top level CMakeLists.txt Qt Location is optional.
=> Fix build failure when Qt Location is not available

plugins/channelrx/chanalyzer/chanalyzer.cpp, swagger/sdrangel/code/qt5/client/SWGChannelAnalyzerSettings.cpp
With this fix, corresponding settings updates are now properly communicated via reverse API.
=> Fix typos in ChannelAnalyzer settings

sdrbase/audio/audioinputdevice.cpp
Fixes a compiler warning:
.../sdrangel/sdrbase/audio/audioinputdevice.cpp:106: warning: format ‘%d’ expects a matching ‘int’ argument [-Wformat=]
=> Fix "More '%' conversions than data arguments"

plugins/samplesource/sdrplayv3/sdrplayv3plugin.cpp
Hi,
SDRPLAY_MAX_DEVICES is used in the API and also already in sdrplayv3input.h. Make it consistent.
Best,
Simon
=> sdrplayv3: use SDRPLAY_MAX_DEVICES in enumOriginDevices()

sdrbase/util/ais.cpp, sdrgui/gui/valuedial.cpp
AIS: Fix string decoding in safety messages for #2094. 
ValueDial: Prevent array being accessed out of range.
=> Two bug fixes

plugins/channelrx/demodam/amdemod.cpp, plugins/channelrx/demodbfm/bfmdemod.cpp, plugins/channelrx/demodbfm/bfmdemod.h, plugins/channelrx/demodbfm/bfmdemodbaseband.cpp, plugins/channelrx/demodbfm/bfmdemodbaseband.h, plugins/channelrx/demodbfm/bfmdemodgui.cpp, plugins/channelrx/demodbfm/bfmdemodsink.cpp, plugins/channelrx/demodnfm/nfmdemod.cpp, plugins/channelrx/demodnfm/nfmdemod.h, plugins/channelrx/demodnfm/nfmdemodbaseband.h, plugins/channelrx/demodnfm/nfmdemodgui.cpp, plugins/channelrx/demodnfm/nfmdemodsink.h, plugins/channelrx/demodssb/ssbdemod.cpp, plugins/channelrx/demodssb/ssbdemodgui.cpp, plugins/channelrx/demodssb/ssbdemodgui.h, plugins/channelrx/demodssb/ssbdemodgui.ui, plugins/channelrx/demodvor/vordemod.cpp, plugins/channelrx/demodwfm/wfmdemod.cpp, sdrbase/dsp/ctcssdetector.h
This patch removes the call to start() in the AM, NFM, WFM, BFM, VOR and SSB demods, to fix #2102
The BFM demod also has additional changes so that the baseband and sink are deleted on stop() to ensure the destructor is called disconnecting the audio sink, and brings the code structure in-line with the other demods.
There are a few changes to the NFM, BFM and SSB demod GUI code to account for the baseband/sink not existing all the time.
Also, there's an unrelated change to the SSB GUI that disables AGC settings when AGC is disabled.
Note that the DSDDemod, M17Demod and FreeDVDemod probably also need the change, but let me know if there's any problems with the patch so far.
=> Don't call start() in demod constructors

sdrbase/settings/mainsettings.cpp
This PR always deletes all configurations except "General" from the configuration file, otherwise when deleting at least one entry from a group the previous last entry wouldn't be deleted (at least on Linux which uses a .conf file with the ini format). For example if you had `configuration-1` and `configuration-2` and you deleted one of them (it doesn't matter which one) the old `configuration-2` wouldn't get deleted.
At this time the only group that doesn't end with a number is "General" and those which end with a number are:
$ grep startsWith sdrbase/settings/mainsettings.cpp
if (groups[i].startsWith("preset"))
else if (groups[i].startsWith("command"))
else if (groups[i].startsWith("featureset"))
else if (groups[i].startsWith("pluginpreset"))
else if …
=> Fix saving configurations after deleting some entries

.github/workflows/sdrangel.yml
This PR tries to work around missing a build failure in the CI for Mac:
```
/Users/runner/work/sdrangel/sdrangel/plugins/channelrx/demoddatv/datvideorender.cpp:282:46: error: no member named 'channels' in 'AVCodecContext'
m_metaData.Channels = m_videoDecoderCtx->channels;
~~~~~~~~~~~~~~~~~  ^
/Users/runner/work/sdrangel/sdrangel/plugins/channelrx/demoddatv/datvideorender.cpp:308:48: error: no member named 'channels' in 'AVCodecContext'
<< " channels: " << m_audioDecoderCtx->channels
~~~~~~~~~~~~~~~~~  ^
/Users/runner/work/sdrangel/sdrangel/plugins/channelrx/demoddatv/datvideorender.cpp:309:54: error: no member named 'channel_layout' in 'AVCodecContext'
<< " channel_layout: " << m_audioDecoderCtx->channel_layout
~~~~~~~~~~~~~~~~~  ^ …
```
=> Fix CI for Mac OS

CMakeLists.txt, plugins/feature/afc/afcgui.cpp, plugins/feature/gs232controller/gs232controller.cpp, plugins/feature/map/webserver.cpp, plugins/feature/map/webserver.h, plugins/feature/pertester/pertester.cpp, plugins/feature/satellitetracker/satellitetracker.cpp, plugins/feature/skymap/webserver.cpp, plugins/feature/skymap/webserver.h, plugins/feature/startracker/startracker.cpp, sdrbase/device/deviceuserargs.cpp, sdrbase/maincore.cpp, sdrbase/settings/mainsettings.cpp, sdrbase/util/airlines.cpp, sdrbase/util/airlines.h, sdrgui/gui/glshaderspectrogram.cpp
This PR fixes some memory leaks found with AddressSanitizer (https://github.com/google/sanitizers/wiki/AddressSanitizer).
Most fixes consist only of adding a missing `delete`.
=> Fix memory leaks

plugins/feature/sid/sidgui.cpp
Fixes a stack exhaustion that happens in some machines/compiler combinations.
Fixes #2119.
I'm adding a `if (m_solarDynamicsObservatory)` as in the constructor.
=> Fix crash when quitting sdrangel when the SID window is open

plugins/feature/morsedecoder/morsedecoderworker.cpp
Add cast in moredecoderworker.cpp to fix Qt6 build.
I've also added a pull request to GGMorse to fix the build on Windows. See: https://github.com/f4exb/ggmorse/pull/1
=> Morse feature: Fix for Qt6 and Windows.

sdrgui/channel/channelgui.cpp, sdrgui/device/devicegui.cpp, sdrgui/feature/featuregui.cpp, sdrgui/gui/devicesetselectiondialog.cpp, sdrgui/gui/devicesetselectiondialog.h, sdrgui/gui/workspaceselectiondialog.cpp, sdrgui/gui/workspaceselectiondialog.h, sdrgui/mainspectrum/mainspectrumgui.cpp
This PR proposes two changes:
* when opening the workspace selection dialog, select the current workspace in the list of workspaces 
* when opening the device selection dialog, select the current device in the list of devices
=> Highlight the current workspace and device in their dialogs

sdrbase/dsp/sigmffilerecord.cpp, sdrbase/dsp/sigmffilerecord.h
Replaced `std::ofstream` by `QFile` to support `resize(qint64)` (or `ftruncate`)
The original code will open _sigmf-meta_ without append flag. It causes file emptied if we don't start any recording after opening it.
Fix potential bug that may cause _sigmf-meta_ saved wrongly without calling `ftruncate`.
Check whether it works on other OS if possible.
=> Fix Sigmf Record: overwriting sigmf-data or sigmf-meta

plugins/samplesource/aaroniartsainput/aaroniartsainputplugin.cpp, plugins/samplesource/audioinput/audioinputplugin.cpp
Many other device pairs have names ending with Input/Output:
"AaroniaRTSA",
"AaroniaRTSAOutput",
"Android SDR Driver",
"AudioCATSISO",
"Audio",
"AudioOutput",
"FileInput",
"FileOutput",
"KiwiSDR",
"LocalInput",
"LocalOutput",
"RemoteInput",
"RemoteOutput",
"RemoteTCPInput",
"SigMFFileInput",
"TestMI",
"TestMOSync",
"TestSink",
"TestSource",
=> Rename some input devices for consistency

sdrbase/mainparser.cpp
All long options must be specified with two hypens.
=> Fix error message

sdrgui/gui/configurationsdialog.ui, sdrgui/gui/featurepresetsdialog.ui, sdrgui/gui/pluginpresetsdialog.ui
This PR aligns the left and right sides of QTreeWidget to the buttons below it, similar to other dialogs.
Before this PR:
After this PR:
They become more similar to this:
=> Remove extra margins from some dialogs

plugins/channelrx/channelpower/channelpowersink.cpp, plugins/channelrx/demodchirpchat/chirpchatdemod.cpp, plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/feature/satellitetracker/satelliteselectiondialog.cpp, plugins/feature/satellitetracker/satellitetracker.cpp, plugins/feature/skymap/skymapgui.cpp, plugins/samplesink/audiooutput/audiooutput.cpp, plugins/samplesink/fileoutput/fileoutput.cpp, sdrgui/gui/tvscreenanalog.cpp
This PR adds some `delete` statements in various destructors.
=> Fix memleaks

plugins/channelrx/demodils/ilsdemod.cpp, plugins/channelrx/demodils/ilsdemod.h, plugins/channelrx/demodils/ilsdemodgui.cpp, sdrbase/resources/webapi/doc/html2/index.html, sdrbase/resources/webapi/doc/swagger/include/ILSDemod.yaml, sdrbase/util/morse.cpp, sdrbase/util/morse.h, swagger/sdrangel/api/swagger/include/ILSDemod.yaml, swagger/sdrangel/code/html2/index.html, swagger/sdrangel/code/qt5/client/SWGILSDemodReport.cpp, swagger/sdrangel/code/qt5/client/SWGILSDemodReport.h
Add various ILS parameters to the Web API channel report.
Add settings for IGYH ILS.
Make parameters in Morse module const.
=> ILS Demod: Add DDM/SDM/Deviation to ILS channel report

plugins/channelrx/heatmap/heatmapgui.cpp, plugins/channelrx/heatmap/heatmapgui.h, plugins/channelrx/heatmap/heatmapgui.ui, plugins/channelrx/heatmap/heatmapsettings.cpp, plugins/channelrx/heatmap/heatmapsettings.h
This PR adds some additional settings to the Heat Map to allow the user to control what data to record, in order to reduce memory requirements for large maps.
It also catches memory allocation errors, so it should fail more gracefully.
=> Heat Map - Add settings to reduce memory requirement

plugins/channelrx/freqscanner/freqscanner.cpp, plugins/channelrx/freqscanner/freqscanner.h, plugins/channelrx/freqscanner/freqscanneraddrangedialog.cpp, plugins/channelrx/freqscanner/freqscanneraddrangedialog.ui, plugins/channelrx/freqscanner/freqscannergui.cpp, plugins/channelrx/freqscanner/freqscannergui.h, plugins/channelrx/freqscanner/readme.md, sdrbase/resources/webapi/doc/html2/index.html, sdrbase/resources/webapi/doc/swagger/include/ChannelActions.yaml, sdrbase/resources/webapi/doc/swagger/include/FreqScanner.yaml, sdrbase/webapi/webapirequestmapper.cpp, sdrbase/webapi/webapiutils.cpp, swagger/sdrangel/api/swagger/include/ChannelActions.yaml, swagger/sdrangel/api/swagger/include/FreqScanner.yaml, swagger/sdrangel/code/html2/index.html, swagger/sdrangel/code/qt5/client/SWGChannelActions.cpp, swagger/sdrangel/code/qt5/client/SWGChannelActions.h, swagger/sdrangel/code/qt5/client/SWGFreqScannerActions.cpp, swagger/sdrangel/code/qt5/client/SWGFreqScannerActions.h, swagger/sdrangel/code/qt5/client/SWGFreqScannerChannelState.cpp, swagger/sdrangel/code/qt5/client/SWGFreqScannerChannelState.h, swagger/sdrangel/code/qt5/client/SWGFreqScannerReport.cpp, swagger/sdrangel/code/qt5/client/SWGFreqScannerReport.h, swagger/sdrangel/code/qt5/client/SWGModelFactory.h
Some updates for the Frequency Scanner for #2108.
- Add scan results to channel report.
- Add current scan state to channel report.
- Add run action to API to start/stop a scan.
Also, add HF ATC as a channel range preset.
=> Frequency scanner: Add scan results to channel report. Add run action to API. Add HF ATC.

sdrgui/mainwindow.cpp
This PR removes a call to m_settings.save() in the destructor of MainWindow because the same call is made when handling the close event which happens just before the call to the destructor when terminating Sdrangel normally, as noted in #2107. When killing Sdrangel with Ctrl+C or similar, neither `closeEvent` nor `~MainWindow` are called so the settings aren't saved anyway.
=> Do not save the settings twice

plugins/channelrx/freqscanner/freqscanner.cpp, plugins/channelrx/freqscanner/freqscannersink.cpp
In the Frequency Scanner, fix a rounding error that could prevent some channels from being scanned, depending on sample rate.
=> Frequency Scanner: Fix rounding error 

plugins/channelrx/demodapt/aptdemodgui.cpp, sdrgui/gui/configurationsdialog.cpp, sdrgui/gui/devicesetpresetsdialog.cpp
In configuration dialogs, don't try to append filename suffix on Android, as we can only write to filename specified by user.
In APT Demod, check for filename suffix when saving image, as QImage::save() will fail without one.
For #2189.
=> Android fixes

plugins/feature/map/readme.md
Suggest two tools can be used to create map images:
* QGIS: overkill but does everything
* gdal2tiles: it's called by QGIS but can be used directly
=> Add details about rendered maps stored locally

sdrbase/webapi/webapiserver.cpp, sdrgui/gui/aboutdialog.cpp, sdrgui/mainwindow.cpp
The API server is accepting commands on port 8091 of all interfaces but the about dialog shows only 127.0.0.1:8091 and it is labeled as the address of the documentation:
and the log messages print an empty string as address:
```
2024-07-20 20:57:50.191 (I) WebAPIServer::start: starting web API server at http://:8091
2024-07-20 20:59:07.028 (I) WebAPIServer::stop: stopped web API server at http://:8091
```
This PR tries to improve the information about the IP address in tha About dialog changing the label and using the address `0.0.0.0` as used in in `httplistener.cpp` and according to the documentation at https://doc.qt.io/qt-6/qhostaddress.html#toString which says that `QHostAddress::Any` is indicated with the address 0.0.0.0 even if it is listening on both IPv4 and IPv6.
```
2024-07-20 …
```
=> Improve indication of API server address

plugins/channelrx/demoddab/dabdemodsink.cpp
The glitches were generated by an int16 integer overflow.
The issue appeared when the audio was near or at the saturation level.
When the input audio signal is saturated, the polyphase filter based interpolation/decimation functions tend to increase the samples values and then make them pass the int16 limits. The int16 sample scale() parameter defeat the min/max limitation.
This fix removes the intermediate int16 type conversion by using the Complex Real type.
fixes https://github.com/f4exb/sdrangel/issues/1978
Also : The audio signal is not decimated anymore if not needed.
=>  Fix audio glitches in the DAB plugin

sdrbase/CMakeLists.txt
On current Ubuntu Noble, unable to compile against CUDA using default sdrbase/CMakeLists.txt due to unsupported find_package(CUDA 9.0).
Instead use:
https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html
See suggestions at:
https://stackoverflow.com/questions/68475502/c-with-cuda-project-in-cmake-gives-error-nvlink-fatal-could-not-open-input
=> Use new find_package(CUDA Toolkit)

CMakeLists.txt, sdrbase/dsp/dspdevicemimoengine.cpp, sdrbase/dsp/dspdevicemimoengine.h, sdrbase/dsp/dspdevicesinkengine.cpp, sdrbase/dsp/dspdevicesinkengine.h, sdrbase/dsp/dspdevicesourceengine.cpp, sdrbase/dsp/dspdevicesourceengine.h, sdrbase/dsp/dspengine.cpp, sdrbase/dsp/dspengine.h, sdrgui/CMakeLists.txt, sdrgui/device/devicegui.cpp, sdrgui/gui/workspace.h, sdrgui/mainwindow.cpp, sdrgui/mainwindow.h
This PR adds some FSMs to MainWindow in order wait for events, while not blocking on the GUI Thread as discussed in #2159 
DSPDevice*Engine: Add signals to indicate when commands have been processed.
DSPDeviceSourceEngine: Fix small memory leak.
DSPEngine::removeDeviceEngineAt: Remove wait to avoid blocking thread. Return QThread to get QThread :finished signal.
DSPEngine::addDevice*Engine: Don't call deleteLater for device*Engine, as these objects are deleted manually in MainWindow, which will crash if deleteLater called first.
I don't quite understand some of the code in MainWindow::sampleSinkCreate and MainWindow::sampleMIMOCreate. In the original code, it does:
const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getMIMOSamplingDevice(deviceIndex);
but …
=> MainWindow: Add FSMs to avoid blocking on GUI Thread

plugins/channelrx/heatmap/heatmapgui.cpp
Catch memory allocation failures when adding data to the chart and disable it. For #2083
=> HeatMap: Fix crash when out of memory

plugins/samplesource/rtlsdr/rtlsdrinput.cpp, plugins/samplesource/rtlsdr/rtlsdrthread.cpp, plugins/samplesource/rtlsdr/rtlsdrthread.h
RTLSDR: Apply driver settings in RTLSDRThread, to avoid blocking main thread. Part of #2159 and #1522
Add sync read for WebAssembly (async read causes a crash - most likely due to libusb for WebAssembly issue).
=> RTLSDR: Apply driver settings in RTLSDRThread

.github/workflows/sdrangel.yml
This patch updates Windows build to use Qt 6.7.3. I've been using this for a while and find it has better UI scaling and multimonitor support than Qt 5. The Mac Arm build has been using it for a while. Fixes #2051.
Can't use Qt 6.8, as the github action qt installer (actually the python qt installer that it uses) doesn't yet support installing qtwebengine extension.
=> Use Qt 6 for Windows github build

sdrgui/gui/glspectrumview.cpp
Accounts for the fact that SSB spectra have duplicated values in adjacent bins. Fixes #2282.
=> Fix spectrum peak measurement for SSB spectra.

plugins/channelrx/remotetcpsink/remotetcpsink.cpp, plugins/channelrx/remotetcpsink/remotetcpsinkbaseband.cpp, plugins/channelrx/remotetcpsink/remotetcpsinksettingsdialog.cpp, plugins/channelrx/remotetcpsink/remotetcpsinksink.cpp
Disable IQ compression when protocol is RTL0, as clients can't support it.
=> RemoteTCPSink: Disable IQ compression for RTL0 protocol.

.github/workflows/snap.yml
This PR adds a github action to build and publish a SDRangel Snap to the Snap Store each time a release tag is created.
=> Add github action to build and publish Snap

sdrsrv/mainserver.cpp
When creating a sink we need to wait for the signal from the sink engine rather than source. Likewise for MIMO. For #2294
=> Server: Use Sink/MIMO signals rather than Source.

.github/workflows/windows.yml
Add a github action for testing code signing on Windows using SignPath. For #1877
I can't test this from my github account, as the build needs to come from https://github.com/f4exb/sdrangel - so will probably take a few tries to get it working...
=> Add github action to test code signing on Windows using SignPath.

plugins/channelrx/demodadsb/adsbdemod.cpp, plugins/channelrx/demodadsb/adsbdemod.h, plugins/channelrx/demodadsb/adsbdemodbaseband.cpp, plugins/channelrx/demodadsb/adsbdemodbaseband.h, plugins/channelrx/demodadsb/adsbdemoddisplaydialog.cpp, plugins/channelrx/demodadsb/adsbdemoddisplaydialog.h, plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodadsb/adsbdemodgui.h, plugins/channelrx/demodadsb/adsbdemodsettings.cpp, plugins/channelrx/demodadsb/adsbdemodsettings.h, plugins/channelrx/demodadsb/adsbdemodsink.cpp, plugins/channelrx/demodadsb/adsbdemodsink.h, plugins/channelrx/demodadsb/adsbdemodsinkworker.cpp, plugins/channelrx/demodadsb/adsbdemodsinkworker.h, plugins/channelrx/demodadsb/adsbdemodworker.cpp, plugins/channelrx/demodadsb/adsbdemodworker.h, plugins/channelrx/demodais/aisdemodgui.ui, plugins/channelrx/freqscanner/freqscanner.cpp, plugins/channelrx/freqscanner/freqscanner.h, plugins/channelrx/freqscanner/freqscannergui.cpp, plugins/channelrx/freqscanner/freqscannergui.ui, plugins/channelrx/freqscanner/freqscannersettings.h, plugins/channelrx/freqscanner/readme.md
Frequency Scanner: Add multiplex mode, to switch between frequencies at fixed intervals, regardless of power level. This allows, for example, AIS and ADS-B data to be received via a single SDR.
ADS-B updated to use settings keys, which helps to avoid updating the entire GUI (which can be slow) when unrelated settings are set.
=> Frequency scanner: Add multiplex mode

.github/workflows/windows.yml
Windows code signing: Use test certificate until release certificate is available.
=> Windows code signing: Use test certificate 

devices/CMakeLists.txt, plugins/samplesource/remotetcpinput/remotetcpinputtcphandler.cpp, plugins/samplesource/remotetcpinput/remotetcpinputtcphandler.h, qrtplib/rtpudptransmitter.cpp, qrtplib/rtpudptransmitter.h, sdrbase/commands/command.cpp, sdrbase/commands/command.h, sdrgui/gui/commandoutputdialog.cpp, sdrgui/gui/commandoutputdialog.h, sdrgui/gui/commandsdialog.cpp, sdrgui/gui/commandsdialog.h, sdrgui/gui/fftwisdomdialog.cpp, sdrgui/gui/fftwisdomdialog.h
This patch adds support for a few more Qt configurations (QT_NO_OPENSSL, QT_NO_NETWORKINTERFACE, !QT_CONFIG(process)) required for the WebAssembly build.
=> Support more Qt configurations

.github/workflows/sdrangel.yml, .github/workflows/windows.yml
3D map and Sky Map are missing from 7.22.3 Windows release, as Qt WebEngine is reported as not found. This PR adds qtwebchannel  package apparently needed by qtwebengine to the github build.
I've also hopefully fixed the latest error reported by SignPath (Needed to add filename in the XML file).
=> Fix missing 3D map and Sky Map from latest Windows release.

plugins/samplesource/sdrplayv3/CMakeLists.txt
Mac build now seems to link to libsdrplay_api.so.3 rather than libsdrplay_api.so.3.15. So patch path to that as well. Should fix #2322. I don't know if there's a better way to do it.
=> SDRplayv3: Patch path to libsdrplay_api.so.3

plugins/feature/demodanalyzer/demodanalyzer.cpp, plugins/feature/demodanalyzer/demodanalyzerworker.cpp, sdrbase/dsp/wavfilerecord.cpp, sdrbase/dsp/wavfilerecord.h
DemodAnalyzer: Ensure sample rate is set in worker. Should fix #2309.
Unrelated to the bug, have added support in Wav File code for meta-data chunks.
=> DemodAnalyzer: Ensure sample rate is set in worker.

plugins/channelrx/demodfreedv/freedvdemod.cpp, plugins/channelrx/demodfreedv/freedvdemodsink.cpp, sdrbase/dsp/dspengine.cpp, sdrbase/dsp/dspengine.h, sdrgui/mainwindow.cpp
This PR fixes a few memory leaks and race conditions noticed while investigating #2315.
In FreeDV:
- Fix buffer overflow by using freedv_get_n_max_speech_samples instead of freedv_get_n_speech_samples
- Fix memory leak for m_speechOut and m_modIn
- Call stop() before delete, to avoid "QThread: Destroyed while thread is still running"
In mainwindow.cpp/dspengine.cpp:
- Fix memory leak by deleting m_deviceSourceEngine after it is last used.
- Fix race condition by connecting to thread before exit is called.
We still have a problem causing the crash in #2315 though - will add a further comment there.
=> Fix a few memory leaks and race conditions

.github/workflows/windows.yml
Use release signing certificate from SignPath, rather than test certificate.
=> Use release signing certificate for Windows installer.

.github/workflows/windows.yml
It appears for release build signing, we get an e-mail with a signing request, that we manually need to approve. Not ideal, and have asked if there's a way around this. For now, increase timeout that the github action will wait for to 30 minutes.
=> Code Signing: Use relative path. Increase approval timeout to 30 minutes.

sdrgui/device/deviceuiset.cpp
Stop device while loading the channels in a device set preset. Fixes #2332
=> Stop device while loading device set.

.github/workflows/windows.yml
Remove unzip step, as it looks like it's not needed. And increase timeout to 1hour.
Hopefully that should now work and we can close #1877
=> Windows code signing update

.github/workflows/sdrangel.yml, .github/workflows/windows.yml
Upload signed releases rather than unsigned releases to Github releases page.
Only sign releases, not all pull requests.
=> Upload signed releases rather than unsigned releases to Github

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodadsb/readme.md
Send username/password in header rather than in URL.
=> ADS-B: Fix OpenSky authentication to enable 4000 API calls per day.

plugins/channelrx/remotetcpsink/remotetcpsinksink.cpp, plugins/samplesink/usrpoutput/readme.md, plugins/samplesink/usrpoutput/usrpoutput.cpp, plugins/samplesink/usrpoutput/usrpoutputsettings.cpp, plugins/samplesink/usrpoutput/usrpoutputsettings.h, plugins/samplesource/usrpinput/readme.md, plugins/samplesource/usrpinput/usrpinput.cpp, plugins/samplesource/usrpinput/usrpinputsettings.cpp, plugins/samplesource/usrpinput/usrpinputsettings.h, sdrbase/channel/channelwebapiutils.cpp, sdrbase/resources/webapi/doc/html2/index.html, sdrbase/resources/webapi/doc/swagger/include/RemoteTCPInput.yaml, sdrbase/resources/webapi/doc/swagger/include/USRP.yaml, swagger/sdrangel/api/swagger/include/USRP.yaml, swagger/sdrangel/code/html2/index.html, swagger/sdrangel/code/qt5/client/SWGRemoteTCPInputReport.cpp, swagger/sdrangel/code/qt5/client/SWGRemoteTCPInputReport.h, swagger/sdrangel/code/qt5/client/SWGUSRPInputSettings.cpp, swagger/sdrangel/code/qt5/client/SWGUSRPInputSettings.h, swagger/sdrangel/code/qt5/client/SWGUSRPOutputSettings.cpp, swagger/sdrangel/code/qt5/client/SWGUSRPOutputSettings.h
Add basic GPIO support for USRP devices for use with Simple PTT - as discussed in #1558.
RemoteTCPSink: Handle client disconnecting immediately.
=> Add GPIO support for USRP devices

sdrgui/gui/crightclickenabler.cpp
This allows for example, selecting the audio output device for visually
impaired.
=> right-click-enabler: Allow activation of the right click action by keyboard

plugins/feature/radiosonde/radiosondegui.cpp, plugins/feature/radiosonde/radiosondegui.h, plugins/feature/radiosonde/radiosondegui.ui, plugins/feature/radiosonde/radiosondesettings.cpp, plugins/feature/radiosonde/radiosondesettings.h, plugins/feature/radiosonde/readme.md, sdrbase/util/sondehub.cpp, sdrbase/util/sondehub.h
Add option to Radiosonde feature to display predicted paths on map.
Fixes incorrect radio type sent to SondeHub.
=> Radiosonde: Add option to display predicted paths.

cmake/Modules/CompilerOptions.cmake
Fix gcc warnings about warning options for #2384.
-Wno-inconsistent-missing-override is a clang only option.
-Woverloaded-virtual is a c++ only option.
=> Fix gcc warnings about warning options

sdrbase/util/radiosonde.cpp, sdrbase/util/radiosonde.h
Fix pressure calculation in Radiosonde demod. Signed value was erroneously extracted as unsigned. Fixes #2242
=> Radiosonde: Fix pressure calculation. 

sdrbase/audio/audiodeviceinfo.cpp
Add 384000 and maximum supported sample rates for Qt 6 AudioDeviceInfo. For #2456.
=> Add 384000 and maximum supported audio sample rates for Qt 6

plugins/channelrx/demodadsb/adsbdemodgui.cpp, plugins/channelrx/demodais/aisdemodgui.cpp, plugins/channelrx/demoddsc/dscdemodgui.cpp, plugins/channelrx/demodendoftrain/endoftraindemodgui.cpp, plugins/channelrx/demodils/ilsdemodgui.cpp, plugins/channelrx/demodnavtex/navtexdemodgui.cpp, plugins/channelrx/demodpacket/packetdemodgui.cpp, plugins/channelrx/demodpager/pagerdemodgui.cpp, plugins/channelrx/demodradiosonde/radiosondedemodgui.cpp, plugins/channelrx/heatmap/heatmapgui.cpp, plugins/channelrx/noisefigure/noisefiguregui.cpp, plugins/channelrx/radioastronomy/radioastronomygui.cpp, plugins/feature/sid/sidgui.cpp, plugins/feature/sid/sidsettingsdialog.cpp, sdrgui/gui/glspectrumgui.cpp, sdrgui/gui/spectrumcalibrationpointsdialog.cpp, sdrgui/gui/spectrummarkersdialog.cpp
Set csv as default filename extension for save file dialogs. For #2506
=> Set csv as default filename extension for save file dialogs. 
