- Readme.md
- ReadmeDeveloper.md
> little typo

- plugins/channelrx/demoddsd/dsddemodgui.ui
- plugins/samplesink/bladerfoutput/bladerfoutputplugin.cpp
- plugins/samplesource/bladerfinput/bladerfinputplugin.cpp
> Typo fixes

- plugins/channelrx/demodbfm/rdsdemod.cpp
- plugins/samplesource/filesource/filesourcegui.cpp
- qrtplib/rtpsession.cpp
Running sdrangel through valgrind and with the -fsanitize compile flags reveal multiple potential issues. This pull request contains patches for the easier ones I came across.
> Sanitizer fixes

- app/main.cpp
- plugins/channelrx/demodbfm/bfmdemodgui.cpp
Running sdrangel through valgrind reveals a number of memory leaks. I'm having difficulty tracking most of them down, but the two patches in this pull request fix two pretty easy ones.
> Memleak fixes

- devices/xtrx/devicextrxshared.cpp
- devices/xtrx/devicextrxshared.h
- swagger/sdrangel/examples/start_stop.py
> Fix typo in start stop

- devices/plutosdr/deviceplutosdrscan.cpp
This patch enables network access for PlutoSDR as mentioned in https://github.com/f4exb/sdrangel/issues/61
> implement networked PlutoSDR

- apple/deploy.sh
- sdrbase/sdrbase.pro
LimeSuite, nanomsg, mirisdr SoapySDR(self-build) and libopus(macports) added.
> Updates in deployment, using libopus from macports.

- flatpak/.gitignore
- flatpak/org.sdrangel.SDRangel.appdata.xml
- flatpak/org.sdrangel.SDRangel.json
- flatpak/sdrangel.desktop
This is a completely unfinished work in progress. Guess there is no way but compiling libiio, libusb, etc. completely from source.
> [WIP] flatpak integration

- plugins/samplesource/filesource/filesourceinput.cpp
> Improve MSVC 2015 compatibility of FileSource plugin

- flatpak/org.sdrangel.SDRangel.appdata.xml
They need manual updating and are not required.
> Remove releases from Flatpak AppData

- plugins/channeltx/modatv/atvmodsource.cpp
> Fix OpenCV constants namespace

- sdrgui/gui/rollupwidget.cpp
> fix tiny build issue on Qt5.15.0 #535

- sdrgui/gui/rollupwidget.cpp
Apply Qt 5.15.0 fix to v5 branch.
> fix tiny build issue on Qt5.15.0

- sdrgui/gui/valuedial.cpp
- sdrgui/gui/valuedialz.cpp
> ValueDial(Z): add virtual keyboard support

- plugins/channeltx/modpacket/packetmod.cpp
- plugins/channeltx/modpacket/packetmodsource.cpp
- plugins/channeltx/modpacket/readme.md
Add some additional error checking and initialisation in the packet modulator. Also fix some typos in the readme.
> Modpacket fixes

- flatpak/org.sdrangel.SDRangel.json
Untested, but should resolve #423.
> Workaround Flatpak issues on Wayland

- sdrgui/gui/channelsdock.cpp
- sdrgui/gui/featuresdock.cpp
- sdrgui/gui/samplingdevicesdock.cpp
- sdrgui/mainwindow.cpp
As I always forget which is which...
> Add tooltips for dock title bar buttons

- plugins/samplesink/fileoutput/readme.md
Specify different data formats depending on sample size
> Fix sdriq file format documentation

- plugins/feature/afc/afc.cpp
- plugins/feature/afc/afcworker.h
- plugins/feature/aprs/aprs.cpp
- plugins/feature/aprs/aprswebapiadapter.cpp
- plugins/feature/demodanalyzer/demodanalyzer.cpp
- plugins/feature/gs232controller/gs232controller.cpp
- plugins/feature/gs232controller/gs232controllerwebapiadapter.cpp
- plugins/feature/map/map.cpp
- plugins/feature/map/mapwebapiadapter.cpp
- plugins/feature/map/readme.md
- plugins/feature/rigctlserver/rigctlserver.cpp
- plugins/feature/rigctlserver/rigctlserver.h
- plugins/feature/rigctlserver/rigctlserverwebapiadapter.cpp
- plugins/feature/simpleptt/simpleptt.cpp
- plugins/feature/startracker/readme.md
- plugins/feature/startracker/startracker.cpp
- plugins/feature/startracker/startracker.h
- plugins/feature/startracker/startrackerwebapiadapter.cpp
- plugins/feature/startracker/startrackerworker.h
- plugins/feature/vorlocalizer/vorlocalizer.cpp
- plugins/feature/vorlocalizer/vorlocalizerplugin.cpp
- plugins/feature/vorlocalizer/vorlocalizerplugin.h
Fix a few small problems in all of the features, as well as some documentation fixes.
> Feature Fixes

- plugins/feature/startracker/readme.md
- plugins/feature/startracker/startrackergui.cpp
- plugins/feature/startracker/startrackergui.h
- plugins/feature/startracker/startrackergui.ui
- plugins/feature/startracker/startrackersettings.cpp
- plugins/feature/startracker/startrackersettings.h
- plugins/feature/startracker/startrackersettingsdialog.cpp
- plugins/feature/startracker/startrackersettingsdialog.ui
- sdrbase/util/units.h
> Star tracker update

- plugins/samplesource/airspyhf/airspyhfgui.cpp
- plugins/samplesource/airspyhf/airspyhfgui.ui
- plugins/samplesource/airspyhf/airspyhfworker.cpp
- plugins/samplesource/airspyhf/readme.md
- sdrbase/dsp/decimatorsfi.h
This PR adds additional 128 and 256 decimation factors for Airspy HF.
> AirspyHF additional decimation factors

- sdrbase/dsp/filerecord.cpp
- sdrbase/dsp/filerecord.h
Add mutex as feed and start/stop can be called from different threads.
> Fix for #795

- sdrbase/dsp/firfilter.h
> Fix impulse response of FIR filter

- plugins/channelrx/demodchirpchat/chirpchatdemod.cpp
- plugins/feature/aprs/aprssettings.cpp
- plugins/feature/aprs/readme.md
> Add basic APRS support to ChirpChatDemod

- plugins/channeltx/moddatv/dvb-s/dvb-s.cpp
> Remove unnecessary zero-padding in DATV mod RS encoder

- plugins/feature/aprs/aprsgui.cpp
- plugins/feature/aprs/aprsgui.h
- plugins/feature/aprs/aprsplugin.cpp
- plugins/feature/aprs/aprssettings.cpp
- plugins/feature/aprs/aprssettings.h
- plugins/feature/aprs/aprssettingsdialog.cpp
- plugins/feature/aprs/aprssettingsdialog.h
- plugins/feature/aprs/aprssettingsdialog.ui
- plugins/feature/aprs/readme.md
- sdrbase/util/aprs.h
- sdrbase/util/units.h
> Add support for choosing different units in APRS feature

- plugins/channelrx/demodadsb/adsbdemodgui.h
- plugins/channelrx/demodvor/vordemodgui.h
- plugins/feature/map/mapgui.h
- plugins/feature/vorlocalizer/vorlocalizergui.h
> Fix assertion when removing all elements from model

- plugins/channelrx/demodadsb/adsbdemodsettings.h
> Update table column array sizes to match number of columns in table.

- external/CMakeLists.txt
- plugins/channelrx/demoddab/dabdemod.cpp
- plugins/channelrx/demoddab/dabdemod.h
- plugins/channelrx/demoddab/dabdemodgui.cpp
- plugins/channelrx/demoddab/dabdemodgui.h
- plugins/channelrx/demoddab/dabdemodgui.ui
- plugins/channelrx/demoddab/dabdemodsink.cpp
- plugins/channelrx/demoddab/dabdemodsink.h
As discussed on #864.
Also fixes external project dependencies on windows.
> Add support for displaying images broadcast in the DAB demodulator GUI

- plugins/channelrx/demodadsb/adsbdemodsink.cpp
- plugins/channelrx/demodpacket/packetdemodgui.cpp
- plugins/channelrx/demodpacket/packetdemodgui.h
- plugins/channelrx/demodpacket/packetdemodsettings.h
- plugins/channelrx/demodpacket/packetdemodsink.cpp
- plugins/channelrx/demodpacket/readme.md
- plugins/channeltx/mod802.15.4/ieee_802_15_4_modsource.cpp
- plugins/channeltx/moddatv/dvb-s/dvb-s.cpp
- plugins/feature/satellitetracker/satellitetrackersgp4.cpp
- plugins/feature/startracker/startrackergui.cpp
This should fix the memory leak reported in #877 as well as a couple of others I've spotted.
> Fix memory leaks

- sdrbase/dsp/wavfilerecord.cpp
- sdrbase/dsp/wavfilerecord.h
> Fix clang compilation error

- plugins/channelrx/demodpacket/packetdemodsink.cpp
Remove magsq check which was far too high for testcase reported in #750
> Improve packet demod performance

- sdrbase/webapi/webapirequestmapper.cpp
> Call init for PerTesterSettings as it contains a list of strings

- plugins/samplesource/sdrplayv3/sdrplayv3input.cpp
- plugins/samplesource/sdrplayv3/sdrplayv3thread.cpp
- plugins/samplesource/sdrplayv3/sdrplayv3thread.h
The error is intermittent but this is preventive maintenance. Fixes #952
> Fix rf update errors in sdrplayv3

- plugins/feature/satellitetracker/readme.md
- plugins/feature/satellitetracker/satellitedevicesettingsgui.cpp
- plugins/feature/satellitetracker/satellitetracker.cpp
- swagger/sdrangel/code/qt5/client/SWGModelFactory.h
Handle missing properties and doppler values out of range.
Regenerate swagger file using latest docker image.
> Fix handling of Satellite Tracker device settings

- plugins/channelrx/radioclock/radioclock.h
- plugins/channelrx/radioclock/radioclockgui.cpp
- plugins/channelrx/radioclock/radioclockgui.ui
- plugins/channelrx/radioclock/radioclocksettings.h
- plugins/channelrx/radioclock/radioclocksink.cpp
- plugins/channelrx/radioclock/radioclocksink.h
- plugins/channelrx/radioclock/readme.md
Also display daylight savings time status.
> Add support for WWVB to Radio Clock plugin

- plugins/feature/antennatools/antennatoolsgui.cpp
- plugins/feature/antennatools/antennatoolsgui.h
- plugins/feature/antennatools/antennatoolsgui.ui
- plugins/feature/antennatools/antennatoolssettings.cpp
- plugins/feature/antennatools/antennatoolssettings.h
- plugins/feature/antennatools/readme.md
Also fix focal length units so not always in metres.
> Antenna Tools: Add surface error parameter for dish gain calculation

- plugins/feature/antennatools/antennatoolsgui.cpp
- plugins/feature/antennatools/antennatoolsgui.h
- plugins/feature/antennatools/antennatoolsgui.ui
- plugins/feature/antennatools/antennatoolsplugin.cpp
- plugins/feature/antennatools/readme.md
Calculate dish effective area.
Adjust beamwidth calculation for 10dB illumination taper and better correlation with measurement.
> Antenna Tools update

- plugins/feature/gs232controller/gs232controller.cpp
- plugins/feature/gs232controller/gs232controller.h
- plugins/feature/gs232controller/gs232controllergui.cpp
- plugins/feature/gs232controller/gs232controllergui.h
- plugins/feature/gs232controller/gs232controllergui.ui
- plugins/feature/gs232controller/gs232controllerplugin.cpp
- plugins/feature/gs232controller/gs232controllersettings.cpp
- plugins/feature/gs232controller/gs232controllersettings.h
- plugins/feature/gs232controller/gs232controllerworker.cpp
- plugins/feature/gs232controller/gs232controllerworker.h
- plugins/feature/gs232controller/readme.md
- swagger/sdrangel/api/swagger/include/GS232Controller.yaml
- swagger/sdrangel/code/qt5/client/SWGGS232ControllerReport.cpp
- swagger/sdrangel/code/qt5/client/SWGGS232ControllerReport.h
- swagger/sdrangel/code/qt5/client/SWGGS232ControllerSettings.cpp
- swagger/sdrangel/code/qt5/client/SWGGS232ControllerSettings.h
Fix broken pipe #1006.
Add onTarget and current and target aziumth and elevation to web report.
Set run/stop button background to yellow when rotator is rotating (not onTarget).
Use floating point value for tolerance setting.
> GS-232 Controller Updates

- plugins/channelrx/chanalyzer/chanalyzergui.ui
- plugins/channelrx/demodadsb/adsbdemodgui.ui
- plugins/channelrx/demodais/aisdemodgui.ui
- plugins/channelrx/demodapt/aptdemodgui.ui
- plugins/channelrx/demoddab/dabdemodgui.ui
- plugins/channelrx/demoddatv/datvdemodgui.ui
- plugins/channelrx/demodpacket/packetdemodgui.ui
- plugins/channelrx/demodpager/pagerdemodgui.ui
- plugins/channelrx/demodvor/vordemodgui.ui
- plugins/channelrx/noisefigure/noisefiguregui.ui
- plugins/channelrx/radioastronomy/radioastronomygui.ui
- plugins/channeltx/mod802.15.4/ieee_802_15_4_modgui.ui
- plugins/channeltx/modais/aismodgui.ui
- plugins/channeltx/modpacket/packetmodgui.ui
- plugins/feature/ais/aisgui.ui
- plugins/feature/antennatools/antennatoolsgui.ui
- plugins/feature/satellitetracker/satellitetrackergui.ui
- plugins/feature/startracker/startrackergui.ui
- sdrgui/gui/rollupwidget.cpp
- sdrgui/gui/rollupwidget.h
And adjust some features / channels to take advantage of it.
> Fix #897 - Add support for vertically expanding widgets to RollupWidget

- plugins/channelrx/demodadsb/adsbdemodgui.cpp
> Center ADS-B map on My Location when map is first opened

- IssueTemplate.md
I would like to contribute to this project in the form of proposing an Issue Template. Reading the Wiki, I saw a section about how this project is fun when adding new features, and not so much when there are issues that turn out to not be reproducible, or worse, an issue with the hardware setup.
Hoping that this issue template can be added to the project and listed under the "Insights" tab of the community page.
Thank you for all that you have done in this project, I have learned so much!
> Propose IssueTemplate

- plugins/channelrx/remotesink/remotesinkbaseband.cpp
> Increase FIFO size in Remote Sink according to baseband sample rate

- sdrbase/util/aprs.cpp
- sdrbase/util/aprs.h
I kept seeing these messages in APRS and didn't understand them. So I read the [APRS Mic-E Spec](http://www.aprs.org/doc/APRS101.PDF) and attempted to implement it.
This is my first attempt, both at implementing Mic-E and writing code in C++. This code isn't tested. I honestly don't know how to test it yet. I'm hoping to get some advice, feedback, and guidance on how best to make this work! Happy to hop on a call or video chat or message on how best to make this happen.
> APRS Mic-E Message Decoding

- plugins/channeltx/moddatv/datvmodgui.ui
> DATV Mod - Increase RF bandwidth slider to 50M

- plugins/channelrx/demoddab/dabdemodsink.cpp
> Fix stereo sound in DAB demod

- plugins/samplesource/usrpinput/usrpinput.cpp
- sdrbase/util/poweroftwo.h
> USRPInput - Ensure IQ buffer size is a power of two, as required by decimators

- sdrbase/util/httpdownloadmanager.cpp
Fix problem with downloading files from Google Drive reported on mailing list. (URL can vary more than first thought).
> HttpDownloadManager - Fix Google Drive downloads

- plugins/feature/gs232controller/gs232controllerworker.cpp
- plugins/feature/gs232controller/gs232controllerworker.h
> Rotator controller - Open/close serial ports in worker thread.

- plugins/samplesource/sdrplayv3/sdrplayv3thread.cpp
- plugins/samplesource/sdrplayv3/sdrplayv3thread.h
> SDRplayInput - Ensure decimation length is power of two

- plugins/channelrx/demodadsb/adsbdemodgui.ui
Use a vertical QSplitter for table and map so user can adjust size used for each.
> ADS-B: Use QSplitter for table and map

- plugins/feature/satellitetracker/satellitetrackersgp4.cpp
> Fix satellite tracks on map when timezone isn't UTC

- plugins/samplesource/usrpinput/usrpinput.cpp
> USRP: Attempt to support radios without AGC

- plugins/channelrx/demodbfm/bfmdemodgui.cpp
Fix missing connection for BFM clear previous text button
> BFM: Fix clear previous text button

- plugins/samplesource/airspy/airspygui.cpp
> Airspy: Add link to documentation

- plugins/samplesource/usrpinput/usrpinput.cpp
> USRP: Catch all exceptions from set_rx_agc

- plugins/feature/map/mapsettings.cpp
> Map: Fix capitalisation of Radiosonde so settings are found. 

- plugins/samplesource/rtlsdr/readme.md
> Fix small typo in rtlsdr readme

- plugins/channelrx/demodadsb/adsbdemodsettings.cpp
- plugins/feature/map/mapsettings.cpp
> Fix QT 5.15.4 map hang

- CMakeLists.txt
> Call find_package for OpenCV on Windows for modatv

- plugins/samplesource/remotetcpinput/remotetcpinput.cpp
> RemoteTCPInput: Use input frequency offset when calculating centre frequency

- plugins/channelrx/demodadsb/adsbdemodgui.cpp
- plugins/channelrx/demodadsb/adsbdemodgui.h
- plugins/channelrx/demodadsb/adsbdemodgui.ui
- plugins/channelrx/demodadsb/adsbdemodnotificationdialog.cpp
- plugins/channelrx/demodadsb/adsbdemodreport.h
- plugins/channelrx/demodadsb/adsbdemodsettings.cpp
- plugins/channelrx/demodadsb/adsbdemodsettings.h
- plugins/channelrx/demodadsb/adsbdemodsinkworker.cpp
- plugins/channelrx/demodadsb/adsbdemodsinkworker.h
- plugins/channelrx/demodadsb/readme.md
- sdrbase/CMakeLists.txt
- sdrbase/util/osndb.cpp
- sdrbase/util/osndb.h
- sdrbase/util/planespotters.cpp
- sdrbase/util/planespotters.h
- sdrbase/util/units.h
Adds TAS, IAS, Mach, Selected Alt, Selected Heading, Turn rate, Roll angle, Autopilot enabled, Vertical and lateral navigation modes, Baro setting, Headwind, OAT, Wind speed and direction, Pressure, Static air temperature, Humidity.
> ADS-B: Add support for decoding Comm-B replies in Mode-S frames

- app/main.cpp
> Remove ? in Windows title bars

- sdrbase/util/iot/visa.cpp
> #1417 - Fix MacOS compilation

- plugins/feature/gs232controller/gs232controller.cpp
- plugins/feature/gs232controller/gs232controller.h
- plugins/feature/gs232controller/gs232controllerworker.cpp
- plugins/feature/gs232controller/gs232controllerworker.h
- plugins/feature/satellitetracker/satellitetracker.cpp
- plugins/feature/satellitetracker/satellitetracker.h
- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackersettings.cpp
- plugins/feature/satellitetracker/satellitetrackersgp4.cpp
- plugins/feature/satellitetracker/satellitetrackersgp4.h
- plugins/feature/satellitetracker/satellitetrackerworker.cpp
- plugins/feature/satellitetracker/satellitetrackerworker.h
This PR updates the Satellite Tracker and Rotator Controller features to use the new threading model as per #1346.
It also fixes a memory corruption bug in the Satellite Tracker.
> Sat tracker and rotator controller threading updates for #1346

- plugins/feature/remotecontrol/remotecontrolgui.cpp
- plugins/feature/remotecontrol/remotecontrolworker.h
Sorry, one more fix for #1417.
> Remote Control: Fix Mac build

- plugins/feature/satellitetracker/satellitetrackerworker.cpp
> Sat Tracker: Fix crash when sat specific AOS command specified. 

- plugins/feature/aprs/aprs.cpp
- plugins/feature/aprs/aprs.h
- plugins/feature/aprs/aprsworker.cpp
- plugins/feature/aprs/aprsworker.h
- plugins/feature/pertester/pertester.cpp
- plugins/feature/pertester/pertester.h
- plugins/feature/pertester/pertesterworker.cpp
- plugins/feature/pertester/pertesterworker.h
- plugins/feature/startracker/startracker.cpp
- plugins/feature/startracker/startracker.h
- plugins/feature/startracker/startrackerworker.cpp
- plugins/feature/startracker/startrackerworker.h
Update threading model in Star Tracker, PER Tester and APRS features for #1346
> #1346: Update threading model in Star Tracker, PER Tester and APRS

- plugins/channelrx/demodadsb/adsbdemodgui.cpp
Fix ADS-B crash when My Position changed and airport database hasn't been loaded for #1287
> #1287 - Fix ADS-B crash when My Position changed

- plugins/samplesource/airspyhf/airspyhfinput.cpp
- plugins/samplesource/airspyhf/airspyhfinput.h
- plugins/samplesource/airspyhf/airspyhfworker.cpp
- plugins/samplesource/airspyhf/airspyhfworker.h
Update airspyhf source to threading model for #1346 which gets it working in MacOS for me, hopefully fixing #1327
I guessed the problem was calling airspyhf_start in a different thread to the callback.
> Update threading in airspyhf source

- qrtplib/rtprandom.cpp
- sdrbase/util/uid.cpp
- swagger/sdrangel/code/qt5/client/SWGHttpRequest.cpp
The first one is 32b the second returns 64b value.
> Replace deprecated QDateTime toTime_t by toSecsSinceEpoch

- plugins/feature/satellitetracker/satellitetracker.cpp
- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackerworker.cpp
- plugins/feature/satellitetracker/satellitetrackerworker.h
Fix for #1445 - Update polar chart on AOS.
Signal AOS/LOS when non real time. 
Fix custom time setting.
> Satellite Tracker: Fix for #1445.

- plugins/samplesource/fileinput/fileinput.cpp
It took mi a while before I found only 16 bit PCM WAV files are supported, this might help others to find out this quicker.
> More descriptive error for broken/unsupported WAV files

- plugins/samplemimo/bladerf2mimo/bladerf2mimogui.cpp
- plugins/samplemimo/limesdrmimo/limesdrmimogui.cpp
- plugins/samplemimo/plutosdrmimo/plutosdrmimogui.cpp
- plugins/samplemimo/xtrxmimo/xtrxmimogui.cpp
- plugins/samplesink/bladerf1output/bladerf1outputgui.cpp
- plugins/samplesink/bladerf2output/bladerf2outputgui.cpp
- plugins/samplesink/hackrfoutput/hackrfoutputgui.cpp
- plugins/samplesink/limesdroutput/limesdroutputgui.cpp
- plugins/samplesink/plutosdroutput/plutosdroutputgui.cpp
- plugins/samplesink/soapysdroutput/soapysdroutputgui.cpp
- plugins/samplesink/usrpoutput/usrpoutputgui.cpp
- plugins/samplesink/xtrxoutput/xtrxoutputgui.cpp
- plugins/samplesource/bladerf1input/bladerf1inputgui.cpp
- plugins/samplesource/bladerf2input/bladerf2inputgui.cpp
- plugins/samplesource/fcdpro/fcdprogui.cpp
- plugins/samplesource/fcdproplus/fcdproplusgui.cpp
- plugins/samplesource/hackrfinput/hackrfinputgui.cpp
- plugins/samplesource/limesdrinput/limesdrinputgui.cpp
- plugins/samplesource/perseus/perseusgui.cpp
- plugins/samplesource/plutosdrinput/plutosdrinputgui.cpp
- plugins/samplesource/remotetcpinput/remotetcpinputgui.cpp
- plugins/samplesource/remotetcpinput/remotetcpinputtcphandler.cpp
- plugins/samplesource/rtlsdr/rtlsdrinput.cpp
- plugins/samplesource/soapysdrinput/soapysdrinputgui.cpp
- plugins/samplesource/usrpinput/usrpinputgui.cpp
- plugins/samplesource/xtrxinput/xtrxinputgui.cpp
For remaining devices.
Note: I don't have most of these SDRs, so couldn't test.
> Adjust number of frequency digits depending whether transverter is enabled

- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackergui.h
- plugins/feature/satellitetracker/satellitetrackersettings.cpp
- plugins/feature/satellitetracker/satellitetrackersettings.h
Save column sort as a setting. Fix deserialize of target satellite. Part of #1474
> Satellite tracker settings

- plugins/feature/demodanalyzer/readme.md
> Fix typo in demod analyzer docs 

- plugins/channelrx/demodais/aisdemodgui.cpp
- plugins/channelrx/demodpager/pagerdemodgui.cpp
- plugins/channelrx/demodradiosonde/radiosondedemodgui.cpp
- plugins/channelrx/radioclock/radioclockgui.cpp
- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackergui.h
- sdrgui/gui/scidoublespinbox.cpp
> Fix unused variable warnings

- cmake/Modules/FindSgp4.cmake
- plugins/channelrx/demodapt/aptdemodimageworker.h
- plugins/feature/satellitetracker/satelliteselectiondialog.cpp
- plugins/feature/satellitetracker/satellitetrackersgp4.cpp
Update Satellite Tracker and APT demod to work with latest version of libsgp4.
You may need to rebuild it.
> libsgp4 update

- plugins/feature/gs232controller/gs232controllergui.cpp
- plugins/feature/gs232controller/gs232controllerworker.cpp
Fix initialisation of serial port. 
Fix crash when serial port not initialised.
> Rotator controller: Fix crash

- plugins/feature/radiosonde/radiosondegui.cpp
> RadioSonde: Fix plotting of heading

- plugins/feature/map/CMakeLists.txt
Which was accidentally disabled.
> Reenable 3D Map

- devices/usrp/deviceusrp.cpp
- devices/usrp/deviceusrpparam.cpp
Use hardcoded values to speed up enumeration of USRP B210.
> Speed up enumeration / opening USRP B210 by using hardcoded values.

- plugins/samplesink/audiooutput/audiooutput.cpp
> Audio Output: Initialise m_running

- plugins/channelrx/noisefigure/noisefigure.cpp
- plugins/channelrx/noisefigure/noisefigureplugin.cpp
- plugins/channelrx/noisefigure/noisefiguresettings.cpp
For noise figure plugin:
Fix saving of power on command in settings.
Add debug when running power on/off scripts.
> Noise figure: Fix saving of power on command setting.

- plugins/channelrx/heatmap/heatmapgui.cpp
> Heat map: Fix crash when chart is not visible.

- plugins/channelrx/demodnavtex/navtexdemodsink.cpp
- plugins/channelrx/demodnavtex/readme.md
- sdrbase/util/navtex.cpp
- sdrbase/util/navtex.h
It seems chars are unsigned on Android!
Thanks for all the commits.
> Fix Navtex Android/clang compilation issues.

- plugins/channelrx/demodft8/ft8demodsettingsdialog.h
- plugins/channelrx/heatmap/heatmapgui.cpp
- sdrbase/maincore.cpp
- sdrgui/gui/dialogpositioner.cpp
- sdrgui/mainwindow.cpp
#1625 fixing errors when compiling using qt6
> fixing errors when compiling using qt6

- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackersettings.cpp
> Correct settings keys for Satellite Tracker settings dialog. 

- plugins/channelrx/radioastronomy/radioastronomygui.cpp
- plugins/channelrx/radioastronomy/radioastronomygui.h
- plugins/channelrx/radioastronomy/radioastronomygui.ui
- plugins/channelrx/radioastronomy/radioastronomysettings.h
- plugins/channelrx/radioastronomy/readme.md
Add UTC date/time column in radiometer table. Implements #1640  
Fix centre frequency display. 
Support smaller bandwidths for SID measurement.
> Radio Astronomy updates

- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackersgp4.cpp
- plugins/feature/startracker/startrackergui.cpp
Also adds target to Star Tracker polar chart. For #1641
> Sat & Star tracker: Plot target on Az/El chart. 

- sdrbase/dsp/glscopesettings.cpp
- sdrbase/dsp/glscopesettings.h
- sdrgui/gui/glscopegui.cpp
- sdrgui/gui/glscopegui.h
Save/restore state of trigger stream index, trigger pre index and freerun button.
Increase number of channels from 4 to 8.
> Scope GUI updates.

- plugins/feature/satellitetracker/satellitetracker.cpp
> Sat Tracker: Add query to TLE download filename, to avoid clashes. 

- sdrgui/CMakeLists.txt
- sdrgui/gui/accessiblevaluedial.h
- sdrgui/gui/accessiblevaluedialz.h
- sdrgui/gui/valuedial.cpp
- sdrgui/gui/valuedial.h
- sdrgui/gui/valuedialz.cpp
- sdrgui/gui/valuedialz.h
- sdrgui/mainwindow.cpp
Add accessibility interface for ValueDial widgets so they work with screen readers. For #1672
> Add accessibility interface for ValueDial widgets

- plugins/channelrx/demodais/aisdemodgui.cpp
- plugins/channelrx/demodais/aisdemodsink.cpp
- plugins/feature/satellitetracker/satellitetracker.cpp
- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackersettings.cpp
- plugins/feature/satellitetracker/satellitetrackersettings.h
- plugins/feature/satellitetracker/satellitetrackersettingsdialog.cpp
- plugins/feature/satellitetracker/satellitetrackersettingsdialog.ui
- plugins/feature/satellitetracker/satellitetrackerworker.cpp
- plugins/feature/satellitetracker/satellitetrackerworker.h
- swagger/sdrangel/api/swagger/include/SatelliteTracker.yaml
- swagger/sdrangel/code/qt5/client/SWGSatelliteTrackerReport.cpp
- swagger/sdrangel/code/qt5/client/SWGSatelliteTrackerReport.h
- swagger/sdrangel/code/qt5/client/SWGSatelliteTrackerSettings.cpp
- swagger/sdrangel/code/qt5/client/SWGSatelliteTrackerSettings.h
Fixes several bugs including #1682
Also add Az/El offset setting.
> Reimplement Doppler correction in Sat Tracker

- plugins/feature/map/mapgui.cpp
- plugins/feature/map/mapgui.h
- plugins/feature/map/osmtemplateserver.h
Change Street Map from WikiMedia to OpenStreetMap, as Wikimedia servers are no longer available. For #1709
> Change Street Map from WikiMedia to OpenStreetMap

- cmake/ci/build_codec2.sh
> Update codec2 repo in build_codec2.sh

- sdrgui/gui/glspectrumview.cpp
> Clear OpenGL buffer with alpha=1

- plugins/channelrx/demoddsd/dsddemodgui.cpp
Connect slot 1/2 on/off buttons in GUI.
For #1752.
> Fix slot 2 audio in DSD Demod

- plugins/channelrx/udpsink/readme.md
The UDPSink is available on Windows installation.
> UDPSink Readme Change

- plugins/channelrx/filesink/filesinksink.cpp
- sdrbase/dsp/filerecordinterface.cpp
In filesink / filerecord. For #1760
> Use QFileInfo to get file extension.

- app/main.cpp
- sdrgui/gui/graphicsdialog.cpp
- sdrgui/gui/graphicsdialog.h
- sdrgui/gui/graphicsdialog.ui
> Add UI scale factor setting for high DPI screens

- cmake/cpack/MacOSXBundleInfo.plist.in
In Info.plist to help fix #1819
> Add description why Microphone, Camera and Location are required on MacOS.

- CMakeLists.txt
- app/main.cpp
- mac/auth.mm
For additional issue identified in #1819
> Request authorization for access to camera and microphone on Mac

- sdrbase/dsp/downchannelizer.cpp
- sdrbase/dsp/upchannelizer.cpp
Need to #include < array > on Windows
> Fix compilation on Windows

- .github/workflows/sdrangel.yml
- external/CMakeLists.txt
Update external/CMakeLists.txt to enable Mac Arm64 build.
Would you mind also looking at the https://github.com/f4exb/sdrangel-windows-libraries/pulls pull requests, please? Thanks.
> Enable Mac Arm64 build

- plugins/channelrx/freqscanner/freqscanneraddrangedialog.cpp
- plugins/channelrx/freqscanner/freqscanneraddrangedialog.ui
Hey, thank you devs for the awesome work. I use SDRAngel to see all the radios being used around me, this preset would help.
> Add FRS-GMRS presets

- .github/workflows/sdrangel.yml
- external/CMakeLists.txt
- plugins/channelrx/freqscanner/freqscanner.cpp
- plugins/channelrx/freqscanner/freqscanner.h
- plugins/channelrx/freqscanner/freqscannergui.cpp
- plugins/channelrx/freqscanner/freqscannersettings.cpp
- plugins/channelrx/freqscanner/freqscannersettings.h
- plugins/feature/map/czml.cpp
- plugins/feature/simpleptt/simplepttgui.cpp
- plugins/samplesource/airspyhf/airspyhfinput.cpp
- plugins/samplesource/sdrplayv3/CMakeLists.txt
- plugins/samplesource/sdrplayv3/sdrplayv3plugin.cpp
- plugins/samplesource/sdrplayv3/sdrplayv3plugin.h
- sdrbase/dsp/datafifo.cpp
- sdrbase/dsp/firfilter.h
- swagger/docker/readme.md
Fix Airspy HF Instant Replay.
Fix SDRplay on Mac arm64.
Map: Remove HTML from labels on 3D map.
Freq Scanner: Stop scanner when tune menu selected.
Add Docker install instructions for swagger build.
And a few other little bits, as per individual commit messages.
> Variety of small fixes

- plugins/channelrx/demodpager/pagerdemod.cpp
> Pager Demod: Add null terminator in UDP packets

- plugins/samplesource/fileinput/fileinput.cpp
- plugins/samplesource/fileinput/fileinput.h
- sdrgui/gui/glspectrumview.cpp
Spectrum Measurements: Fix frequency for SSB spectrums. Fixes #1944.
File Input: Fix seeking over .wav header
> Couple of bug fixes

- plugins/feature/satellitetracker/satellitetracker.cpp
- plugins/feature/satellitetracker/satellitetracker.h
- plugins/feature/satellitetracker/satellitetrackergui.cpp
- plugins/feature/satellitetracker/satellitetrackersettings.cpp
Update default TLEs to latest URLs as previous GOES TLE no longer exists.
Add GUI error if TLEs not downloaded.
> Sat Tracker: Update default TLEs to latest URLs. 

- external/CMakeLists.txt
- plugins/samplesource/sdrplayv3/CMakeLists.txt
Update Mac build to use SDRplay API 3.14 and UHD 4.6.0.
> Mac build updates

- plugins/channelrx/demodadsb/readme.md
Update by request of Reddit user for Airplanes.Live support and port.
> Add Airplanes.Live at request of user

- plugins/channeltx/modpacket/packetmodsource.cpp
- sdrbase/util/ax25.cpp
Can use multi VIAs like `VIA1,VIA2,VIA3` or no VIA at all
Fix #2037
> AX.25 Packet: packetmod supports multi Via; packetdemod fix H bit

- sdrbase/util/rtpsink.h
> Fix typo in comments [ci skip]

- plugins/feature/skymap/skymapsettings.h
Add missing include to fix Qt6 build.
> Fix Qt6 build

- .github/workflows/sdrangel.yml
- external/CMakeLists.txt
Fix ggmorse paths for Mac build.
> Fix ggmorse paths on mac

- sdrbase/resources/webapi.qrc
This PR adds missing file that resulted in warnings printed in the terminal and errors printed in the web page at http://localhost:8091/doc/swagger-ui/index.html#/Instance/instanceConfigGet
```
Resolver error at paths./sdrangel/config.get.responses.200.schema.properties.featuresetpresets.items.properties.featureConfigs.items.properties.config.properties.SIDSettings.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./sdrangel/config.get.responses.200.schema.properties.workingFeatureSetPreset.properties.featureConfigs.items.properties.config.properties.SIDSettings.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./sdrangel/config.get.responses.200.schema.properties.featuresetpresets.items.properties.featureConfigs.items.properties.config …
```
> Add missing .yaml files to webapi.qrc

- plugins/channelrx/demodais/aisdemodgui.cpp
- plugins/channelrx/demodapt/aptdemodgui.cpp
- plugins/channelrx/demoddab/dabdemodgui.cpp
- plugins/channelrx/demoddsc/dscdemodgui.cpp
- plugins/channelrx/demodendoftrain/endoftraindemodgui.cpp
- plugins/channelrx/demodpacket/packetdemodgui.cpp
- plugins/channelrx/demodradiosonde/radiosondedemodgui.cpp
- plugins/channelrx/radioastronomy/radioastronomygui.cpp
- plugins/feature/aprs/aprsgui.cpp
- plugins/feature/satellitetracker/satnogs.h
- plugins/feature/startracker/startrackergui.cpp
- plugins/feature/startracker/startrackerworker.cpp
- sdrbase/util/aprs.cpp
- sdrbase/util/astronomy.cpp
- sdrbase/util/astronomy.h
- sdrbase/util/fits.cpp
- sdrbase/util/maidenhead.cpp
- sdrbase/util/units.h
Replace QRegExp with QRegularExpression. Needed for WASM build.
> Remove use of deprecated QRegExp.

- plugins/samplesource/sdrplayv3/CMakeLists.txt
Update post build step in Mac ARM build to use 3.15. #2167
Update external/windows link to latest sdrangel-windows-libraries. #2155
> SDRplay 3.15 updates

- plugins/samplesource/sdrplayv3/sdrplayv3gui.cpp
- plugins/samplesource/sdrplayv3/sdrplayv3input.cpp
Add SDRPLAY_RSPdxR2_ID support. For #2155
Requires https://github.com/f4exb/sdrangel-windows-libraries/pull/23 for Windows build.
> SDRplayV3Input: Add SDRPLAY_RSPdxR2_ID support.

- plugins/channelrx/demodils/ilsdemodgui.cpp
ILS Demod: Save frequency when switching between LOC and G/S. Set frequency for ident when in G/S mode. Fixes #2177
> ILS Demod: Save frequency when switching between LOC and G/S. Set frequency for ident when in G/S mode.

- plugins/channelrx/demodais/aisdemod.cpp
- plugins/channelrx/demodais/aisdemodgui.cpp
- plugins/channelrx/demodais/readme.md
- plugins/feature/ais/aisgui.cpp
- sdrbase/util/ais.cpp
- sdrgui/gui/configurationsdialog.cpp
- sdrgui/gui/configurationsdialog.h
AIS: Validate message length and ignore invalid messages. Fixes #2125
> AIS: Validate message length. Fixes #2125

- swagger/sdrangel/examples/scanner.py
I think the original may have been some accidental C++. :slightly_smiling_face:
> Update scanner.py: fix print to stderr

- plugins/channelrx/wdsprx/wdsprxfmdialog.ui
- plugins/channelrx/wdsprx/wdsprxgui.cpp
This PR fixes a small typo and a copy and paste error.
> Fix/wdsp UI

- sdrbase/device/deviceapi.cpp
Fix bug introduced here:
https://github.com/f4exb/sdrangel/commit/b85419c56a119a8b07be7c512b0ba0c5cd614b68#diff-343de58ea3ced5ed293cef49a04f79e0155d64f26af234ad22960403a0217b22
Fixes #2266.
> Fix DeviceAPI::deserialize. 

- swagger/sdrangel/examples/add_channel.py
- swagger/sdrangel/examples/rtlsdr_settings.py
- swagger/sdrangel/examples/rx_test.py
This PR updates a couple of the swagger example python scripts to python3. Part of #2297
> Update some example scripts to python3

- plugins/channelrx/demodpager/pagerdemodnotificationdialog.cpp
Pager: Add notifications based on alpha and numeric columns. Implements #2319
> Pager: Add Add notifications based on alpha and numeric columns. 

- plugins/channelrx/demodadsb/adsbdemodsinkworker.cpp
- plugins/channelrx/demodadsb/adsbdemodsinkworker.h
> ADSB: Include adsbdemodsettings.h

- sdrbase/util/sondehub.cpp
> RadioSonde: Limit precision of floating point numbers sent to SondeHub.

- plugins/feature/sid/sidgui.cpp
Can't use pointers to items in QList as they can be moved.
> SID: Fix crash when loading data from .csv.

- plugins/feature/radiosonde/radiosondegui.cpp
- plugins/feature/radiosonde/radiosondegui.h
- sdrbase/util/sondehub.cpp
> Radiosonde: Rate limit position updates to SondeHub.

- plugins/channeltx/modssb/ssbmod.cpp
> Fix SSB Mod Morse keyer

- sdrbase/feature/featurewebapiutils.cpp
- sdrbase/feature/featurewebapiutils.h
- sdrbase/mainparser.cpp
- sdrbase/mainparser.h
- sdrgui/mainwindow.cpp
- sdrgui/mainwindow.h
For GUI version of SDRangel, add --start command line option to start all devices and features automatically.
#2218
> Add --start command line option to start all devices and features. 

- snap/snapcraft.yaml
> Update snap to use UHD 4.7.

- .github/workflows/mac.yml
Set MACOSX_DEPLOYMENT_TARGET to 12.0 so app can run on MacOS 12. For #2395
> Mac x64 build for Mac OS 12

- sdrbase/channel/channelwebapiutils.cpp
- sdrbase/channel/channelwebapiutils.h
ChannelWebAPIUtils: Add double version of patchDeviceSetting. Fix #2428
> ChannelWebAPIUtils: Add double version of patchDeviceSetting.

- plugins/feature/satellitetracker/satellitetrackerworker.cpp
- plugins/feature/satellitetracker/satellitetrackerworker.h
Fix doppler correction in Satellite Tracker, as it currently causes a crash if used.
> Fix sat tracker doppler crash

- plugins/channelrx/demodnavtex/navtexdemodsink.cpp
- plugins/channelrx/remotesink/remotesinksink.cpp
- plugins/channeltx/remotesource/remotesourcesource.cpp
- plugins/samplemimo/metismiso/metismisoudphandler.cpp
Fix build with Qt 6.9.0.
This should fix the Github mac build action.
> Fix build with Qt 6.9.0.

- .github/workflows/sdrangel.yml
- .github/workflows/windows.yml
Try to fix Windows CI build. For #2441
> Try to fix Windows CI build

- plugins/channelrx/remotetcpsink/remotetcpsinksink.cpp
- plugins/samplesource/remotetcpinput/remotetcpinputtcphandler.cpp
RemoteTCP: Add support for SDR_RX_SAMPLE_24BIT=OFF. For #2470
> RemoteTCP: Add support for SDR_RX_SAMPLE_24BIT=OFF

- .github/workflows/mac.yml
- .github/workflows/sdrangel.yml
- .github/workflows/windows.yml
Update Qt version to 6.9.1 on Windows and Mac. Might help with #2481
> Update Qt version to 6.9.1 on Windows and Mac. 

- .github/workflows/sdrangel.yml
- .github/workflows/windows.yml
- plugins/channelrx/demoddatv/datvdemodgui.h
Fix type forward declaration to match definition. For #140
> Fix type forward declaration

- plugins/feature/gs232controller/gs232controllergui.cpp
- plugins/feature/gs232controller/gs232controllergui.h
- plugins/feature/gs232controller/gs232controllergui.ui
- plugins/feature/gs232controller/gs232controllersettings.cpp
- plugins/feature/gs232controller/gs232controllersettings.h
- plugins/feature/gs232controller/gs232protocol.cpp
- plugins/feature/gs232controller/gs232protocol.h
- plugins/feature/gs232controller/readme.md
Rotator Controller: Add line ending setting for GS-232 protocol. For #2486
> Rotator Controller: Add line ending setting for GS-232 protocol.

- sdrgui/mainwindow.cpp
Fix moving features to another workspace. #2501
> Fix moving features to another workspace.
